-- =============================================================================
-- Forma — complete database setup, in one paste.
--
-- GENERATED by scripts/db/bundle.mjs from supabase/migrations/*.sql. Do not edit this file;
-- edit the migrations and re-run `npm run db:bundle`. They stay the source of truth.
--
-- HOW TO RUN
--   Supabase dashboard -> SQL Editor -> New query -> paste all of this -> Run.
--   It should finish with "Success. No rows returned".
--
-- Safe to re-run: every statement is guarded (create ... if not exists, drop policy if exists),
-- which is also how an existing project is upgraded.
--
-- ONE THING TO EDIT: the last section makes the coach an admin. Put his real sign-in address
-- there before running, or the admin screen — where purchases are activated — stays locked.
-- =============================================================================

-- =============================================================================
-- 0001_init.sql — tables, triggers, row-level security, grants
-- =============================================================================

-- =============================================================================
-- Forma — 0001_init: extensions, tables, triggers, RLS policies, grants.
-- Contract: docs/SPEC.md §8. Idempotent: safe to re-run in the SQL editor.
-- Apply order:
--   0001_init.sql → 0002_functions.sql → 0003_storage.sql → 0004_content_seed.sql
--   → seed.sql (admins, optional)
--
-- Re-running a single file is safe and converges: tables use `if not exists`,
-- constraints are dropped and re-added by name, policies and functions are
-- replaced. Run the whole set in order after pulling changes.
--
-- The bounds added below are `not valid`: Postgres enforces them on every insert
-- and update from now on, but does not re-check rows written before this file was
-- applied, so upgrading a live database can never fail on old data. Once you have
-- cleaned any legacy rows you can promote one with
--   alter table public.<table> validate constraint <name>;
-- (docs/SETUP.md §8). A fresh database has no old rows, so nothing differs there.
--
-- Search path: every function pins `pg_catalog, public, extensions` because
-- `citext` lives in `public` on some projects and in `extensions` on others.
-- =============================================================================

create extension if not exists citext;
create extension if not exists pgcrypto;

-- PostgREST exposes `public`; anon/authenticated need schema usage only.
grant usage on schema public to anon, authenticated;

-- Supabase grants EXECUTE on new functions to anon/authenticated through default
-- privileges, which a plain `revoke … from public` does not undo. Turn the default
-- off first, then grant explicitly per function below.
alter default privileges in schema public revoke execute on functions from public, anon, authenticated;

-- -----------------------------------------------------------------------------
-- Generic trigger: bump updated_at on every update.
-- -----------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = pg_catalog, public, extensions
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- Trigger functions are resolved when the trigger is created, never at fire time.
revoke execute on function public.set_updated_at() from public, anon, authenticated;

-- -----------------------------------------------------------------------------
-- current_email() — the caller's *verified* email, or null.
--
-- Never trust the `email` claim in the JWT: it is whatever the auth provider put
-- there, and a provider that returns unverified addresses (or a project with
-- "Confirm email" turned off) would let anyone mint a token for the coach's
-- address. This reads auth.users by the token's subject instead and only answers
-- for a confirmed, live, unbanned user. Everything email-keyed (admins,
-- entitlements, storage) goes through it.
-- -----------------------------------------------------------------------------
create or replace function public.current_email()
returns citext
language sql
stable
security definer
set search_path = pg_catalog, public, extensions
as $$
  select u.email::citext
  from auth.users u
  where u.id = auth.uid()
    and u.email is not null
    and u.email <> ''
    and u.email_confirmed_at is not null
    and u.deleted_at is null
    and (u.banned_until is null or u.banned_until <= now());
$$;

revoke execute on function public.current_email() from public, anon;
grant execute on function public.current_email() to authenticated;

-- -----------------------------------------------------------------------------
-- normalize_email() — the single email validator (create_order + admin_add_purchase).
-- Raises `invalid_email` (P0001) instead of returning null so both callers behave
-- identically; see the error convention in 0002_functions.sql.
-- -----------------------------------------------------------------------------
create or replace function public.normalize_email(p_email text)
returns citext
language plpgsql
immutable
set search_path = pg_catalog, public, extensions
as $$
declare
  v_email text := lower(trim(coalesce(p_email, '')));
begin
  if length(v_email) > 254
     or v_email !~ '^[a-z0-9][a-z0-9._%+-]*@[a-z0-9](?:[a-z0-9-]*[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)*\.[a-z]{2,24}$' then
    raise exception 'invalid_email' using errcode = 'P0001', hint = 'Enter a valid email address';
  end if;
  return v_email::citext;
end;
$$;

revoke execute on function public.normalize_email(text) from public, anon, authenticated;

-- =============================================================================
-- profiles — one row per auth user, created by trigger on auth.users insert.
-- =============================================================================
create table if not exists public.profiles (
  id               uuid primary key references auth.users (id) on delete cascade,
  email            citext not null,
  display_name     text,
  avatar_seed      text not null default encode(gen_random_bytes(4), 'hex'),
  locale           text not null default 'ru' check (locale in ('ru', 'en')),
  -- UserTrainingProfile (src/lib/training/types.ts), owned by the app.
  training_profile jsonb,
  fitness_index    int check (fitness_index is null or fitness_index between 0 and 100),
  fitness_level    int check (fitness_level is null or fitness_level between 1 and 3),
  onboarded_at     timestamptz,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

comment on table public.profiles is 'App profile per auth user. Email mirrors auth.users.email (citext).';

-- Size limits on everything the client writes. display_name and avatar_seed are
-- relayed to every athlete through get_leaderboard, so an unbounded name would be
-- a denial-of-service on other people's leaderboard: those two are also repaired
-- in place, because they are read by other users.
update public.profiles set display_name = left(display_name, 60) where length(display_name) > 60;
update public.profiles set avatar_seed = encode(gen_random_bytes(4), 'hex')
  where avatar_seed !~ '^[A-Za-z0-9_-]{1,64}$';

alter table public.profiles drop constraint if exists profiles_email_len;
alter table public.profiles add constraint profiles_email_len
  check (length(email::text) <= 254)
  not valid;
alter table public.profiles drop constraint if exists profiles_display_name_len;
alter table public.profiles add constraint profiles_display_name_len
  check (display_name is null or length(display_name) <= 60)
  not valid;
alter table public.profiles drop constraint if exists profiles_avatar_seed_fmt;
alter table public.profiles add constraint profiles_avatar_seed_fmt
  check (avatar_seed ~ '^[A-Za-z0-9_-]{1,64}$')
  not valid;
-- UserTrainingProfile is a small object (~30 fields); 8 KB is 10× headroom.
alter table public.profiles drop constraint if exists profiles_training_profile_size;
alter table public.profiles add constraint profiles_training_profile_size
  check (training_profile is null or octet_length(training_profile::text) <= 8192)
  not valid;

alter table public.profiles enable row level security;

drop trigger if exists set_updated_at on public.profiles;
create trigger set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

-- Runs as the function owner (postgres) because the inserting role is
-- supabase_auth_admin, which has no privileges on public.profiles.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
begin
  insert into public.profiles (id, email, display_name)
  values (
    new.id,
    -- Email OTP always has an email; coalesce keeps auth signups from failing
    -- if another provider without an email is ever enabled.
    left(coalesce(new.email, ''), 254),
    -- Signup metadata is client-controlled: clamp it to the column limit instead
    -- of letting a crafted signup store a huge name (see profiles_display_name_len).
    left(
      nullif(trim(coalesce(new.raw_user_meta_data ->> 'name', new.raw_user_meta_data ->> 'full_name')), ''),
      60
    )
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

revoke execute on function public.handle_new_user() from public, anon, authenticated;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Keep profiles.email in sync when a user changes their email in Supabase Auth,
-- so purchases (matched by email) keep resolving to the right person.
create or replace function public.handle_user_email_change()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
begin
  if new.email is distinct from old.email and new.email is not null then
    update public.profiles set email = left(new.email, 254) where id = new.id;
  end if;
  return new;
end;
$$;

revoke execute on function public.handle_user_email_change() from public, anon, authenticated;

drop trigger if exists on_auth_user_email_updated on auth.users;
create trigger on_auth_user_email_updated
  after update of email on auth.users
  for each row execute function public.handle_user_email_change();

-- Policies -------------------------------------------------------------------
-- Owner reads own row.
drop policy if exists "profiles: owner select" on public.profiles;
create policy "profiles: owner select"
  on public.profiles for select
  to authenticated
  using (id = auth.uid());

-- Owner updates own row (column privileges below stop email/id changes).
drop policy if exists "profiles: owner update" on public.profiles;
create policy "profiles: owner update"
  on public.profiles for update
  to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

-- Fallback insert for users created before the trigger existed: the row must be
-- the caller's own id and carry the caller's own email.
drop policy if exists "profiles: owner insert fallback" on public.profiles;
create policy "profiles: owner insert fallback"
  on public.profiles for insert
  to authenticated
  with check (id = auth.uid() and email = public.current_email());

-- No delete policy: rows go away with the auth user (on delete cascade).

-- Grants (minimal) ------------------------------------------------------------
revoke all on public.profiles from anon, authenticated;
grant select, insert on public.profiles to authenticated;
-- Column-level update: email and id can never be changed by the client.
grant update (display_name, avatar_seed, locale, training_profile, fitness_index, fitness_level, onboarded_at)
  on public.profiles to authenticated;

-- =============================================================================
-- admins — emails allowed to manage purchases and videos.
-- =============================================================================
create table if not exists public.admins (
  email      citext primary key,
  created_at timestamptz not null default now()
);

comment on table public.admins is 'Coach / staff emails. Insert via SQL editor (see supabase/seed.sql).';

alter table public.admins enable row level security;

-- Security definer so it can read admins regardless of RLS; stable for planning.
-- Keyed on the *verified* email (current_email()), never on the raw JWT claim.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public, extensions
as $$
  select exists (
    select 1 from public.admins a
    where a.email = public.current_email()
  );
$$;

revoke execute on function public.is_admin() from public, anon;
grant execute on function public.is_admin() to authenticated;

-- Only admins can see who the admins are; nobody can write through the API.
drop policy if exists "admins: admins select" on public.admins;
create policy "admins: admins select"
  on public.admins for select
  to authenticated
  using (public.is_admin());

revoke all on public.admins from anon, authenticated;
grant select on public.admins to authenticated;

-- =============================================================================
-- purchases — email ↔ course access. Written by RPCs only (never directly).
-- =============================================================================
create table if not exists public.purchases (
  id           uuid primary key default gen_random_uuid(),
  email        citext not null,
  course_id    text not null,
  status       text not null default 'pending' check (status in ('pending', 'active', 'refunded')),
  source       text,
  locale       text,
  note         text,
  created_at   timestamptz not null default now(),
  activated_at timestamptz,
  updated_at   timestamptz not null default now(),
  unique (email, course_id)
);

comment on table public.purchases is 'Orders and entitlements. pending → active (coach confirms payment) → refunded.';

-- Bounds on everything create_order() can put here (it validates too; the table is
-- the backstop for the admin RPCs and for direct SQL).
update public.purchases set source = left(source, 40) where length(source) > 40;
update public.purchases set note = left(note, 500) where length(note) > 500;
update public.purchases set locale = null where locale is not null and locale not in ('ru', 'en');

alter table public.purchases drop constraint if exists purchases_email_len;
alter table public.purchases add constraint purchases_email_len
  check (length(email::text) <= 254)
  not valid;
alter table public.purchases drop constraint if exists purchases_course_id_fmt;
alter table public.purchases add constraint purchases_course_id_fmt
  check (course_id ~ '^[a-z0-9_]{2,40}$')
  not valid;
alter table public.purchases drop constraint if exists purchases_source_len;
alter table public.purchases add constraint purchases_source_len
  check (source is null or length(source) <= 40)
  not valid;
alter table public.purchases drop constraint if exists purchases_locale_fmt;
alter table public.purchases add constraint purchases_locale_fmt
  check (locale is null or locale in ('ru', 'en'))
  not valid;
alter table public.purchases drop constraint if exists purchases_note_len;
alter table public.purchases add constraint purchases_note_len
  check (note is null or length(note) <= 500)
  not valid;

create index if not exists purchases_email_idx on public.purchases (email);
create index if not exists purchases_status_created_idx on public.purchases (status, created_at desc);

alter table public.purchases enable row level security;

drop trigger if exists set_updated_at on public.purchases;
create trigger set_updated_at
  before update on public.purchases
  for each row execute function public.set_updated_at();

-- Admins can do everything through the API (list/activate/refund/add).
drop policy if exists "purchases: admins all" on public.purchases;
create policy "purchases: admins all"
  on public.purchases for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- Customers have NO direct read of purchases: the row carries the coach's internal
-- `note` and `source`. They see what they own through the `my_entitlements` view
-- (security definer, course_id + activated_at only — 0002_functions.sql).
drop policy if exists "purchases: owner select" on public.purchases;

-- No anon policies: anonymous visitors only go through create_order().

revoke all on public.purchases from anon, authenticated;
grant select, insert, update, delete on public.purchases to authenticated;

-- =============================================================================
-- courses / workouts — the catalogue the backend enforces, mirrored from
-- content/courses/*.ts by supabase/migrations/0004_content_seed.sql
-- (generated: node scripts/content/gen-seed.mjs).
--
-- courses  → create_order() only accepts ids that exist here.
-- workouts → workout_sessions_guard clamps points to the engine ceiling derived
--            from base_points, so a tampered client cannot inflate them.
-- =============================================================================
create table if not exists public.courses (
  id         text primary key check (id ~ '^[a-z0-9_]{2,40}$'),
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

comment on table public.courses is 'Allowlist of real course ids (generated seed, 0004_content_seed.sql).';

create table if not exists public.workouts (
  -- Workout ids are unique inside a course, not globally (see getWorkout()).
  course_id   text not null references public.courses (id) on delete cascade,
  id          text not null check (id ~ '^[a-z0-9_]{2,40}$'),
  base_points int not null check (base_points between 1 and 250),
  primary key (course_id, id)
);

comment on table public.workouts is 'Workout basePoints per course (generated seed, 0004_content_seed.sql).';

alter table public.courses enable row level security;
alter table public.workouts enable row level security;

-- Public catalogue data: readable by signed-in users, written only by migrations.
drop policy if exists "courses: read" on public.courses;
create policy "courses: read" on public.courses for select to authenticated using (true);
drop policy if exists "workouts: read" on public.workouts;
create policy "workouts: read" on public.workouts for select to authenticated using (true);

revoke all on public.courses from anon, authenticated;
revoke all on public.workouts from anon, authenticated;
grant select on public.courses to authenticated;
grant select on public.workouts to authenticated;

-- -----------------------------------------------------------------------------
-- has_entitlement() — does the caller own this course? Admins own everything.
-- Security definer: customers cannot read public.purchases at all.
-- -----------------------------------------------------------------------------
create or replace function public.has_entitlement(p_course_id text)
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public, extensions
as $$
  select public.is_admin() or exists (
    select 1
    from public.purchases p
    where p.status = 'active'
      and p.course_id = p_course_id
      and p.email = public.current_email()
  );
$$;

revoke execute on function public.has_entitlement(text) from public, anon;
grant execute on function public.has_entitlement(text) to authenticated;

-- =============================================================================
-- order_throttle — per-IP sliding window for the anonymous create_order() RPC.
-- Written only by create_order (security definer); no client ever touches it.
-- =============================================================================
create table if not exists public.order_throttle (
  bucket       text primary key,
  window_start timestamptz not null default now(),
  hits         int not null default 0
);

comment on table public.order_throttle is 'Rate-limit buckets for create_order(); key is the client IP or "global".';

create index if not exists order_throttle_window_idx on public.order_throttle (window_start);

alter table public.order_throttle enable row level security;
-- No policies at all: only the security-definer RPC (owner: postgres) writes here.
revoke all on public.order_throttle from anon, authenticated;

-- =============================================================================
-- user_course_state — per-user, per-course adaptive state.
-- =============================================================================
create table if not exists public.user_course_state (
  user_id            uuid not null references auth.users (id) on delete cascade,
  course_id          text not null,
  scale              numeric(4, 2) not null default 1.0 check (scale between 0.3 and 2),
  current_node_index int not null default 0 check (current_node_index >= 0),
  completed_node_ids text[] not null default '{}',
  updated_at         timestamptz not null default now(),
  primary key (user_id, course_id)
);

-- Course id shape and a bound on the node list (a course has ~40 nodes; 500 is
-- room for every course plus repeats, and caps the row at a few kilobytes).
alter table public.user_course_state drop constraint if exists user_course_state_course_id_fmt;
alter table public.user_course_state add constraint user_course_state_course_id_fmt
  check (course_id ~ '^[a-z0-9_]{2,40}$')
  not valid;
alter table public.user_course_state drop constraint if exists user_course_state_nodes_bounded;
alter table public.user_course_state add constraint user_course_state_nodes_bounded
  check (
    cardinality(completed_node_ids) <= 500
    and (
      cardinality(completed_node_ids) = 0
      -- every element is a node id, which also bounds the row size
      or array_to_string(completed_node_ids, ',') ~ '^[a-z0-9_]{2,40}(,[a-z0-9_]{2,40})*$'
    )
  )
  not valid;

alter table public.user_course_state enable row level security;

drop trigger if exists set_updated_at on public.user_course_state;
create trigger set_updated_at
  before update on public.user_course_state
  for each row execute function public.set_updated_at();

-- Owner has full control of own rows.
drop policy if exists "user_course_state: owner all" on public.user_course_state;
create policy "user_course_state: owner all"
  on public.user_course_state for all
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

revoke all on public.user_course_state from anon, authenticated;
grant select, insert, update, delete on public.user_course_state to authenticated;

-- =============================================================================
-- workout_sessions — one row per started workout; completed when completed_at is set.
-- =============================================================================
create table if not exists public.workout_sessions (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references auth.users (id) on delete cascade,
  course_id    text not null,
  node_id      text not null,
  workout_id   text not null,
  difficulty   text check (difficulty is null or difficulty in ('easier', 'normal', 'harder')),
  scale        numeric(4, 2),
  -- PrescribedWorkout / ExerciseResult[] (src/lib/training/types.ts)
  prescribed   jsonb,
  results      jsonb,
  rpe          int check (rpe is null or rpe between 1 and 10),
  feeling      text check (feeling is null or feeling in ('great', 'ok', 'hard', 'pain')),
  completion   numeric(4, 3) check (completion is null or completion between 0 and 1),
  -- Client-computed by the engine, then clamped by workout_sessions_guard to the
  -- ceiling of this workout (see the constraints below).
  points       int not null default 0,
  duration_sec int,
  calories     int,
  started_at   timestamptz not null default now(),
  completed_at timestamptz,
  local_date   date not null
);

-- Hard bounds. The absolute points ceiling is the engine maximum:
-- basePoints 250 × harder 1.25 × streak 1.2 = 375 (docs/SPEC.md §7); the trigger
-- narrows it per workout. Rows written before this migration are clamped in place
-- as well, because the leaderboard sums them for everyone to see.
update public.workout_sessions set points = 375 where points > 375;
update public.workout_sessions set points = 0 where points < 0;
update public.workout_sessions set duration_sec = 21600 where duration_sec > 21600;
update public.workout_sessions set calories = 5000 where calories > 5000;

alter table public.workout_sessions drop constraint if exists workout_sessions_points_check;
alter table public.workout_sessions drop constraint if exists workout_sessions_points_ceiling;
alter table public.workout_sessions add constraint workout_sessions_points_ceiling
  check (points between 0 and 375)
  not valid;
alter table public.workout_sessions drop constraint if exists workout_sessions_ids_fmt;
alter table public.workout_sessions add constraint workout_sessions_ids_fmt
  check (
    course_id ~ '^[a-z0-9_]{2,40}$'
    and node_id ~ '^[a-z0-9_]{2,40}$'
    and workout_id ~ '^[a-z0-9_]{2,40}$'
  )
  not valid;
alter table public.workout_sessions drop constraint if exists workout_sessions_duration_sec_check;
alter table public.workout_sessions drop constraint if exists workout_sessions_duration_bounded;
alter table public.workout_sessions add constraint workout_sessions_duration_bounded
  check (duration_sec is null or duration_sec between 0 and 21600)
  not valid;
alter table public.workout_sessions drop constraint if exists workout_sessions_calories_check;
alter table public.workout_sessions drop constraint if exists workout_sessions_calories_bounded;
alter table public.workout_sessions add constraint workout_sessions_calories_bounded
  check (calories is null or calories between 0 and 5000)
  not valid;
-- A prescribed workout is ~5 KB of JSON; 64 KB is generous and stops a client from
-- filling the database through its own rows.
alter table public.workout_sessions drop constraint if exists workout_sessions_json_size;
alter table public.workout_sessions add constraint workout_sessions_json_size
  check (
    (prescribed is null or octet_length(prescribed::text) <= 65536)
    and (results is null or octet_length(results::text) <= 65536)
  )
  not valid;

create index if not exists workout_sessions_user_completed_idx
  on public.workout_sessions (user_id, completed_at);
create index if not exists workout_sessions_course_completed_idx
  on public.workout_sessions (course_id, completed_at);
create index if not exists workout_sessions_user_local_date_idx
  on public.workout_sessions (user_id, local_date);

alter table public.workout_sessions enable row level security;

-- -----------------------------------------------------------------------------
-- workout_sessions_guard — everything the leaderboard depends on is decided here,
-- never by the client:
--   * started_at / completed_at come from the server clock, and a completed_at
--     that is already set never moves (no back-dating into another week);
--   * local_date must be within a day of the server date (no backfill, no future);
--   * points are clamped to the engine ceiling for THIS workout:
--     base_points × difficulty (0.8 / 1.0 / 1.25) × repeat (0.5) × max streak
--     bonus (1.2) — docs/SPEC.md §7;
--   * at most 4 completed sessions per local day;
--   * user/course/node/workout are frozen after the insert.
-- Course ownership is enforced by the insert policy (has_entitlement).
-- Security definer so it can read public.workouts and count the caller's own rows
-- without extra grants; every query is keyed by new.user_id.
-- -----------------------------------------------------------------------------
create or replace function public.workout_sessions_guard()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_uid     uuid := auth.uid();
  v_base    int;
  v_factor  numeric;
  v_repeat  boolean;
  v_ceiling int;
  v_today   int;
begin
  -- RLS says the same thing; repeating it here keeps the counters below from being
  -- probed with somebody else's user_id (the trigger runs before the check).
  if v_uid is not null and new.user_id is distinct from v_uid then
    raise exception 'not_owner' using errcode = '42501';
  end if;

  if tg_op = 'INSERT' then
    new.started_at := now();
    if new.completed_at is not null then
      new.completed_at := now();
    end if;
  else
    -- A session's identity is fixed at insert: an update finishes the session it
    -- started, it cannot move points to another user, course or node.
    new.user_id    := old.user_id;
    new.course_id  := old.course_id;
    new.node_id    := old.node_id;
    new.workout_id := old.workout_id;

    new.started_at := old.started_at;
    if old.completed_at is not null then
      new.completed_at := old.completed_at;
    elsif new.completed_at is not null then
      new.completed_at := now();
    end if;
  end if;

  -- local_date is the athlete's own calendar day, and time zones reach UTC ± 14h,
  -- so exactly one day either side of the server date is allowed.
  if tg_op = 'INSERT' or new.local_date is distinct from old.local_date then
    if new.local_date < current_date - 1 or new.local_date > current_date + 1 then
      raise exception 'invalid_local_date' using errcode = 'P0001',
        hint = 'local_date must be within one day of the server date';
    end if;
  end if;

  select w.base_points into v_base
  from public.workouts w
  where w.course_id = new.course_id and w.id = new.workout_id;

  -- Unknown workout id (content newer than 0004_content_seed.sql): fall back to the
  -- smallest ceiling the content model allows (basePoints ≥ 60) instead of failing,
  -- so training keeps working while abuse stays bounded.
  v_base := coalesce(v_base, 60);

  v_factor := case new.difficulty
                when 'easier' then 0.8
                when 'harder' then 1.25
                else 1.0
              end;

  select exists (
    select 1
    from public.workout_sessions s
    where s.user_id = new.user_id
      and s.course_id = new.course_id
      and s.node_id = new.node_id
      and s.completed_at is not null
      and s.id <> new.id
  ) into v_repeat;

  v_ceiling := ceil(v_base * v_factor * (case when v_repeat then 0.5 else 1 end) * 1.2);
  new.points := least(greatest(coalesce(new.points, 0), 0), v_ceiling);

  if new.completed_at is not null and (tg_op = 'INSERT' or old.completed_at is null) then
    select count(*) into v_today
    from public.workout_sessions s
    where s.user_id = new.user_id
      and s.local_date = new.local_date
      and s.completed_at is not null
      and s.id <> new.id;

    if v_today >= 4 then
      raise exception 'too_many_sessions_today' using errcode = 'P0001',
        hint = 'At most 4 completed sessions per day';
    end if;
  end if;

  return new;
end;
$$;

revoke execute on function public.workout_sessions_guard() from public, anon, authenticated;

drop trigger if exists workout_sessions_guard on public.workout_sessions;
create trigger workout_sessions_guard
  before insert or update on public.workout_sessions
  for each row execute function public.workout_sessions_guard();

-- Owner reads/updates/deletes own rows; inserts must carry the caller's user_id.
drop policy if exists "workout_sessions: owner select" on public.workout_sessions;
create policy "workout_sessions: owner select"
  on public.workout_sessions for select
  to authenticated
  using (user_id = auth.uid());

-- Insert also requires an active purchase of the course: a locked course cannot be
-- trained, and its sessions cannot appear on its leaderboard. Update stays open so a
-- session started before a refund can still be finished.
drop policy if exists "workout_sessions: owner insert" on public.workout_sessions;
create policy "workout_sessions: owner insert"
  on public.workout_sessions for insert
  to authenticated
  with check (user_id = auth.uid() and public.has_entitlement(course_id));

drop policy if exists "workout_sessions: owner update" on public.workout_sessions;
create policy "workout_sessions: owner update"
  on public.workout_sessions for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

drop policy if exists "workout_sessions: owner delete" on public.workout_sessions;
create policy "workout_sessions: owner delete"
  on public.workout_sessions for delete
  to authenticated
  using (user_id = auth.uid());

revoke all on public.workout_sessions from anon, authenticated;
grant select, insert, update, delete on public.workout_sessions to authenticated;

-- =============================================================================
-- daily_logs — steps per local day; points recomputed server-side.
-- =============================================================================
create table if not exists public.daily_logs (
  user_id    uuid not null references auth.users (id) on delete cascade,
  local_date date not null,
  steps      int not null check (steps between 0 and 100000),
  points     int not null default 0,
  note       text,
  updated_at timestamptz not null default now(),
  primary key (user_id, local_date)
);

update public.daily_logs set note = left(note, 500) where length(note) > 500;
alter table public.daily_logs drop constraint if exists daily_logs_note_len;
alter table public.daily_logs add constraint daily_logs_note_len
  check (note is null or length(note) <= 500)
  not valid;

alter table public.daily_logs enable row level security;

drop trigger if exists set_updated_at on public.daily_logs;
create trigger set_updated_at
  before update on public.daily_logs
  for each row execute function public.set_updated_at();

-- Mirrors the engine rule (docs/SPEC.md §7): 30 at goal, +5 per extra 1000, cap 60, 0 below.
create or replace function public.steps_points(p_steps int, p_goal int default 7000)
returns int
language sql
immutable
set search_path = pg_catalog, public, extensions
as $$
  select case
    when p_steps is null or p_steps < p_goal then 0
    else least(60, 30 + 5 * ((p_steps - p_goal) / 1000))
  end;
$$;

-- Nobody calls this over the API; the trigger below calls it as its owner.
revoke execute on function public.steps_points(int, int) from public, anon, authenticated;

-- The client sends points too, but the server always overwrites them from steps
-- so the leaderboard cannot be gamed by editing the payload. Security definer so
-- steps_points() needs no grant to authenticated.
create or replace function public.daily_logs_set_points()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
begin
  new.points := public.steps_points(new.steps);
  return new;
end;
$$;

revoke execute on function public.daily_logs_set_points() from public, anon, authenticated;

drop trigger if exists daily_logs_points on public.daily_logs;
create trigger daily_logs_points
  before insert or update on public.daily_logs
  for each row execute function public.daily_logs_set_points();

-- Owner has full control of own rows, but writes are limited to the days an athlete
-- can honestly log: yesterday's week back (a forgotten day) and tomorrow (time zones
-- ahead of the server). Without this, step points could be backfilled or pre-filled
-- for any date. Reads and deletes stay unrestricted in time.
drop policy if exists "daily_logs: owner all" on public.daily_logs;

drop policy if exists "daily_logs: owner select" on public.daily_logs;
create policy "daily_logs: owner select"
  on public.daily_logs for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "daily_logs: owner insert" on public.daily_logs;
create policy "daily_logs: owner insert"
  on public.daily_logs for insert
  to authenticated
  with check (
    user_id = auth.uid()
    and local_date between current_date - 7 and current_date + 1
  );

drop policy if exists "daily_logs: owner update" on public.daily_logs;
create policy "daily_logs: owner update"
  on public.daily_logs for update
  to authenticated
  using (user_id = auth.uid())
  with check (
    user_id = auth.uid()
    and local_date between current_date - 7 and current_date + 1
  );

drop policy if exists "daily_logs: owner delete" on public.daily_logs;
create policy "daily_logs: owner delete"
  on public.daily_logs for delete
  to authenticated
  using (user_id = auth.uid());

revoke all on public.daily_logs from anon, authenticated;
grant select, insert, update, delete on public.daily_logs to authenticated;

-- =============================================================================
-- benchmarks — personal records from test/benchmark nodes.
-- =============================================================================
create table if not exists public.benchmarks (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users (id) on delete cascade,
  key         text not null check (key ~ '^[a-z0-9_]{2,60}$'),
  value       numeric not null,
  unit        text not null,
  recorded_at timestamptz not null default now()
);

-- Records are reps / seconds / meters / calories / rounds, rounded to 2 decimals by
-- the app: bound both the magnitude and the precision, and keep the unit a short tag.
alter table public.benchmarks drop constraint if exists benchmarks_value_bounded;
alter table public.benchmarks add constraint benchmarks_value_bounded
  check (value between 0 and 1000000 and value = round(value, 3))
  not valid;
alter table public.benchmarks drop constraint if exists benchmarks_unit_fmt;
alter table public.benchmarks add constraint benchmarks_unit_fmt
  check (unit ~ '^[a-z_]{1,16}$')
  not valid;

create index if not exists benchmarks_user_key_recorded_idx
  on public.benchmarks (user_id, key, recorded_at desc);

alter table public.benchmarks enable row level security;

-- Owner has full control of own rows.
drop policy if exists "benchmarks: owner all" on public.benchmarks;
create policy "benchmarks: owner all"
  on public.benchmarks for all
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

revoke all on public.benchmarks from anon, authenticated;
grant select, insert, update, delete on public.benchmarks to authenticated;

-- =============================================================================
-- 0002_functions.sql — create_order, entitlements, admin RPCs, leaderboard
-- =============================================================================

-- =============================================================================
-- Forma — 0002_functions: RPCs and views (orders, entitlements, admin, leaderboard).
-- Requires 0001_init.sql. Idempotent (create or replace).
--
-- Error convention: app-level validation failures raise with errcode P0001 and a
-- short machine-readable message (invalid_email, invalid_course, …); permission
-- failures use 42501; missing rows use P0002. src/lib/api/errors.ts maps these.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- create_order — anonymous order from the landing. Upserts a pending purchase.
--
-- This is the only write anonymous visitors can make, so it carries the whole
-- abuse budget:
--   * the course must exist in public.courses (0004_content_seed.sql), so junk
--     rows cannot be invented;
--   * per-IP sliding window (public.order_throttle) caps bulk submissions;
--   * a per-email advisory lock makes the "max 10 pending" check race-free
--     (it used to be read-then-insert);
--   * an `active` purchase is never touched — not its status, not its source or
--     locale — so knowing a customer's email buys nothing.
-- -----------------------------------------------------------------------------
create or replace function public.create_order(
  p_email     text,
  p_course_id text,
  p_locale    text default 'ru',
  p_source    text default 'landing'
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  -- Per IP per hour. Generous for a household or an office behind one NAT,
  -- small enough that scripted bulk inserts stop being interesting.
  c_ip_limit     constant int := 30;
  -- No IP header (direct SQL, a proxy that strips it): one shared bucket. Kept
  -- high on purpose — it must not turn a launch day into a self-inflicted outage.
  c_global_limit constant int := 200;
  c_window       constant interval := interval '1 hour';

  v_email   citext;
  v_locale  text;
  v_source  text;
  v_headers json;
  v_forward text[];
  v_ip      text;
  v_bucket  text;
  v_limit   int;
  v_hits    int;
  v_pending int;
  v_id      uuid;
begin
  v_email := public.normalize_email(p_email);

  if p_course_id is null
     or p_course_id !~ '^[a-z0-9_]{2,40}$'
     or not exists (select 1 from public.courses c where c.id = p_course_id) then
    raise exception 'invalid_course' using errcode = 'P0001', hint = 'Unknown course id';
  end if;

  v_locale := case when p_locale in ('ru', 'en') then p_locale else 'ru' end;
  v_source := left(coalesce(nullif(trim(p_source), ''), 'landing'), 40);

  -- Client IP as the platform reports it; any parsing problem falls back to the
  -- global bucket rather than to no limit at all.
  begin
    v_headers := nullif(current_setting('request.headers', true), '')::json;
  exception when others then
    v_headers := null;
  end;

  -- `cf-connecting-ip` is written by the edge and cannot be spoofed by the caller.
  -- In `x-forwarded-for` only the LAST entry was added by the proxy in front of us;
  -- everything before it is whatever the client chose to send.
  v_forward := string_to_array(coalesce(v_headers ->> 'x-forwarded-for', ''), ',');
  v_ip := coalesce(
    nullif(btrim(coalesce(v_headers ->> 'cf-connecting-ip', '')), ''),
    nullif(btrim(coalesce(v_headers ->> 'x-real-ip', '')), ''),
    nullif(btrim(coalesce(v_forward[cardinality(v_forward)], '')), '')
  );

  if v_ip is null then
    v_bucket := 'global';
    v_limit  := c_global_limit;
  else
    v_bucket := left(v_ip, 45);
    v_limit  := c_ip_limit;
  end if;

  -- Sliding window: the bucket restarts once its window is older than c_window.
  -- Postgres has no autonomous transactions, so a call that raises rolls back its
  -- own increment: only orders that actually landed spend the budget, and the
  -- counter parks at the limit instead of running away.
  insert into public.order_throttle as t (bucket, window_start, hits)
  values (v_bucket, now(), 1)
  on conflict (bucket) do update
    set window_start = case when t.window_start < now() - c_window then now() else t.window_start end,
        hits         = case when t.window_start < now() - c_window then 1 else t.hits + 1 end
  returning t.hits into v_hits;

  if v_hits > v_limit then
    raise exception 'too_many_orders' using errcode = 'P0001', hint = 'Too many orders from this address, try again later';
  end if;

  -- Serialize everything for this email so the pending count cannot be raced.
  perform pg_advisory_xact_lock(hashtextextended('forma:create_order:' || v_email::text, 0));

  -- Abuse guard: a real customer can have at most one pending row per course.
  select count(*) into v_pending
  from public.purchases
  where email = v_email and status = 'pending';

  if v_pending >= 10 then
    raise exception 'too_many_pending' using errcode = 'P0001', hint = 'Too many pending orders for this email';
  end if;

  insert into public.purchases (email, course_id, status, source, locale)
  values (v_email, p_course_id, 'pending', v_source, v_locale)
  on conflict (email, course_id) do update
    set updated_at = now(),
        source     = excluded.source,
        locale     = coalesce(excluded.locale, purchases.locale),
        -- A refunded row becomes a new pending order (the coach still has to
        -- confirm payment before it grants anything).
        status     = 'pending'
    where purchases.status <> 'active'
  returning id into v_id;

  if v_id is null then
    -- The row is active: left untouched, and the caller gets the same id as before.
    select p.id into v_id
    from public.purchases p
    where p.email = v_email and p.course_id = p_course_id;
  end if;

  return v_id;
end;
$$;

revoke execute on function public.create_order(text, text, text, text) from public;
grant execute on function public.create_order(text, text, text, text) to anon, authenticated;

-- -----------------------------------------------------------------------------
-- my_entitlements — active courses of the signed-in user.
--
-- Security *definer* (the default for a view): customers have no read policy on
-- public.purchases at all, because the row carries the coach's internal `note` and
-- `source`. This projects the two columns they may see, filtered by their verified
-- email. Dropped and recreated so re-running the file also flips the option on a
-- database created by an earlier version.
-- -----------------------------------------------------------------------------
drop view if exists public.my_entitlements;
create view public.my_entitlements
with (security_invoker = false)
as
  select p.course_id, p.activated_at
  from public.purchases p
  where p.status = 'active'
    and p.email = public.current_email();

revoke all on public.my_entitlements from anon, authenticated;
grant select on public.my_entitlements to authenticated;

-- -----------------------------------------------------------------------------
-- admin_set_purchase_status — activate / refund / reset a purchase.
-- -----------------------------------------------------------------------------
create or replace function public.admin_set_purchase_status(p_id uuid, p_status text)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
begin
  if not public.is_admin() then
    raise exception 'not_admin' using errcode = '42501';
  end if;

  if p_status is null or p_status not in ('pending', 'active', 'refunded') then
    raise exception 'invalid_status' using errcode = 'P0001';
  end if;

  update public.purchases
  set status       = p_status,
      -- First activation stamps activated_at; re-activation keeps the original date.
      activated_at = case when p_status = 'active' then coalesce(activated_at, now()) else activated_at end,
      updated_at   = now()
  where id = p_id;

  if not found then
    raise exception 'not_found' using errcode = 'P0002';
  end if;
end;
$$;

revoke execute on function public.admin_set_purchase_status(uuid, text) from public, anon;
grant execute on function public.admin_set_purchase_status(uuid, text) to authenticated;

-- -----------------------------------------------------------------------------
-- admin_add_purchase — manual activation (bank transfer, gift, support case).
-- -----------------------------------------------------------------------------
create or replace function public.admin_add_purchase(
  p_email     text,
  p_course_id text,
  p_note      text default null
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_email citext;
  v_id    uuid;
begin
  if not public.is_admin() then
    raise exception 'not_admin' using errcode = '42501';
  end if;

  -- Same validator as create_order(): one regex, one behaviour.
  v_email := public.normalize_email(p_email);

  -- Admins may grant a course that is not in the catalogue yet (a pre-sale), so
  -- only the id shape is enforced here — unlike create_order().
  if p_course_id is null or p_course_id !~ '^[a-z0-9_]{2,40}$' then
    raise exception 'invalid_course' using errcode = 'P0001';
  end if;

  insert into public.purchases (email, course_id, status, source, note, activated_at)
  values (v_email, p_course_id, 'active', 'admin', left(nullif(trim(p_note), ''), 500), now())
  on conflict (email, course_id) do update
    set status       = 'active',
        activated_at = coalesce(purchases.activated_at, now()),
        note         = coalesce(excluded.note, purchases.note),
        updated_at   = now()
  returning id into v_id;

  return v_id;
end;
$$;

revoke execute on function public.admin_add_purchase(text, text, text) from public, anon;
grant execute on function public.admin_add_purchase(text, text, text) to authenticated;

-- -----------------------------------------------------------------------------
-- get_leaderboard — top N by points (+ the caller's own row), never exposes emails.
--   p_period    'week' (current ISO week, UTC) | 'all'
--   p_course_id null → global (workout points + step points); id → that course only
-- -----------------------------------------------------------------------------
create or replace function public.get_leaderboard(
  p_period    text default 'week',
  p_course_id text default null,
  p_limit     int  default 100
)
returns table (
  user_id      uuid,
  display_name text,
  avatar_seed  text,
  points       bigint,
  rank         bigint,
  is_me        boolean
)
language plpgsql
stable
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  -- Defence in depth: the engine ceiling (basePoints 250 × harder 1.25 × streak 1.2)
  -- and the step-points cap. workout_sessions_guard already clamps per workout, but
  -- the board is the one place every athlete sees, so it clamps again.
  c_max_session_points constant int := 375;
  c_max_step_points    constant int := 60;

  v_me        uuid := auth.uid();
  v_limit     int  := least(greatest(coalesce(p_limit, 100), 1), 500);
  v_week_ts   timestamp;
  v_from      timestamptz;
  v_from_date date;
begin
  if v_me is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;

  if p_period is null or p_period not in ('week', 'all') then
    raise exception 'invalid_period' using errcode = 'P0001';
  end if;

  if p_course_id is not null and p_course_id !~ '^[a-z0-9_]{2,40}$' then
    raise exception 'invalid_course' using errcode = 'P0001';
  end if;

  -- Monday 00:00 UTC of the current ISO week.
  v_week_ts   := date_trunc('week', now() at time zone 'utc');
  v_from      := v_week_ts at time zone 'utc';
  v_from_date := v_week_ts::date;

  return query
  with s as (
    select ws.user_id as uid, sum(least(greatest(ws.points, 0), c_max_session_points))::bigint as pts
    from public.workout_sessions ws
    where ws.completed_at is not null
      and ws.completed_at <= now()
      and (p_period = 'all' or ws.completed_at >= v_from)
      and (p_course_id is null or ws.course_id = p_course_id)
    group by ws.user_id
  ),
  d as (
    select dl.user_id as uid, sum(least(greatest(dl.points, 0), c_max_step_points))::bigint as pts
    from public.daily_logs dl
    -- Never count a day that has not happened yet (time zones ahead of the server
    -- reach current_date + 1).
    where p_course_id is null
      and dl.local_date <= current_date + 1
      and (p_period = 'all' or dl.local_date >= v_from_date)
    group by dl.user_id
  ),
  totals as (
    select coalesce(s.uid, d.uid) as uid,
           coalesce(s.pts, 0) + coalesce(d.pts, 0) as pts
    from s
    full outer join d on d.uid = s.uid
  ),
  ranked as (
    select t.uid, t.pts, rank() over (order by t.pts desc, t.uid) as rnk
    from totals t
    where t.pts > 0
  ),
  top as (
    select r.uid, r.pts, r.rnk from ranked r order by r.rnk, r.uid limit v_limit
  ),
  me as (
    select r.uid, r.pts, r.rnk from ranked r where r.uid = v_me
    union all
    -- Caller without points yet: last place, 0 points.
    select v_me, 0::bigint, (select count(*) from ranked) + 1
    where not exists (select 1 from ranked r where r.uid = v_me)
  ),
  rows_out as (
    select * from top
    union
    select * from me
  )
  select
    ro.uid,
    -- Clamped again on the way out: this row is relayed to every other athlete.
    left(coalesce(nullif(trim(p.display_name), ''), 'Athlete ' || left(ro.uid::text, 4)), 60),
    left(coalesce(p.avatar_seed, left(ro.uid::text, 8)), 64),
    ro.pts,
    ro.rnk,
    ro.uid = v_me
  from rows_out ro
  left join public.profiles p on p.id = ro.uid
  order by ro.rnk, ro.uid;
end;
$$;

revoke execute on function public.get_leaderboard(text, text, int) from public, anon;
grant execute on function public.get_leaderboard(text, text, int) to authenticated;

-- -----------------------------------------------------------------------------
-- get_my_totals — home screen numbers for the caller (security invoker: RLS
-- already limits both tables to own rows).
--   points   = workout points + step points, all time
--   workouts = completed sessions
--   minutes  = sum(duration_sec) / 60 of completed sessions
-- -----------------------------------------------------------------------------
create or replace function public.get_my_totals()
returns table (points bigint, workouts bigint, minutes bigint)
language sql
stable
security invoker
set search_path = pg_catalog, public, extensions
as $$
  select
    coalesce((select sum(ws.points) from public.workout_sessions ws
              where ws.user_id = auth.uid() and ws.completed_at is not null), 0)::bigint
    + coalesce((select sum(dl.points) from public.daily_logs dl
                where dl.user_id = auth.uid()), 0)::bigint                       as points,
    coalesce((select count(*) from public.workout_sessions ws
              where ws.user_id = auth.uid() and ws.completed_at is not null), 0)::bigint as workouts,
    coalesce((select sum(ws.duration_sec) from public.workout_sessions ws
              where ws.user_id = auth.uid() and ws.completed_at is not null), 0)::bigint / 60 as minutes;
$$;

revoke execute on function public.get_my_totals() from public, anon;
grant execute on function public.get_my_totals() to authenticated;

-- =============================================================================
-- 0003_storage.sql — the private videos bucket and its access policies
-- =============================================================================

-- =============================================================================
-- Forma — 0003_storage: private `videos` bucket + access policies.
-- Requires 0001_init.sql (purchases, has_entitlement, is_admin). Idempotent.
--
-- Object naming convention (docs/SETUP.md §5):
--   videos/<course_id>/<exercise_id>.<lang>.mp4   → needs an active purchase of <course_id>
--   videos/shared/<exercise_id>.<lang>.mp4        → any signed-in user
-- Content references them as `storage:videos/<course_id>/<file>`; the app turns
-- that into a short-lived signed URL (src/lib/api/storage.ts).
-- =============================================================================

insert into storage.buckets (id, name, public)
values ('videos', 'videos', false)
on conflict (id) do nothing;

-- Read: signed-in users with an active purchase of the course in the first path
-- segment, everyone signed-in for `shared/`, and admins for everything.
-- The entitlement test lives in public.has_entitlement() (security definer, keyed
-- on the verified email) because customers cannot read public.purchases directly.
drop policy if exists "videos: entitled select" on storage.objects;
create policy "videos: entitled select"
  on storage.objects for select
  to authenticated
  using (
    bucket_id = 'videos'
    and (
      (storage.foldername(name))[1] = 'shared'
      or public.has_entitlement((storage.foldername(name))[1])
    )
  );

-- Write: admins only (upload from the Dashboard or a signed-in admin session).
drop policy if exists "videos: admin insert" on storage.objects;
create policy "videos: admin insert"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'videos' and public.is_admin());

drop policy if exists "videos: admin update" on storage.objects;
create policy "videos: admin update"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'videos' and public.is_admin())
  with check (bucket_id = 'videos' and public.is_admin());

drop policy if exists "videos: admin delete" on storage.objects;
create policy "videos: admin delete"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'videos' and public.is_admin());

-- No anon policies: the bucket is private and never listed publicly.

-- =============================================================================
-- 0004_content_seed.sql — the course and workout catalogue the backend enforces
-- =============================================================================

-- =============================================================================
-- Forma — 0004_content_seed: the course / workout catalogue the backend enforces.
--
-- GENERATED FILE — do not edit by hand.
-- Regenerate with:  node scripts/content/gen-seed.mjs
-- Source of truth:  content/courses/*.ts (validated by src/content/registry.ts)
--
-- Requires 0001_init.sql. Idempotent: upserts every row, then deletes what content
-- no longer has. Re-apply it after every content change that touches course ids,
-- workout ids or basePoints — create_order() rejects unknown course ids and
-- workout_sessions_guard clamps points to base_points from here.
-- =============================================================================

insert into public.courses (id, sort_order) values
  ('start', 1),
  ('engine', 2),
  ('dumbbells', 3),
  ('kettlebell', 4),
  ('athlete', 5)
on conflict (id) do update set sort_order = excluded.sort_order;

insert into public.workouts (course_id, id, base_points) values
  ('start', 'w_benchmark_four_rounds', 150),
  ('start', 'w_circuit_no_jump', 100),
  ('start', 'w_emom_12', 100),
  ('start', 'w_hinge_core_1', 100),
  ('start', 'w_hinge_core_2', 100),
  ('start', 'w_hinge_core_3', 100),
  ('start', 'w_hinge_core_4', 100),
  ('start', 'w_squat_push_1', 100),
  ('start', 'w_squat_push_2', 100),
  ('start', 'w_squat_push_3', 100),
  ('start', 'w_squat_push_4', 100),
  ('start', 'w_test_start', 80),
  ('engine', 'w_bench_burpees', 150),
  ('engine', 'w_bench_cindy', 150),
  ('engine', 'w_chipper_a', 110),
  ('engine', 'w_chipper_b', 120),
  ('engine', 'w_easy_flow', 90),
  ('engine', 'w_engine_amrap10', 100),
  ('engine', 'w_engine_amrap15', 110),
  ('engine', 'w_engine_emom12', 100),
  ('engine', 'w_engine_tabata', 100),
  ('engine', 'w_hinge_core_a', 100),
  ('engine', 'w_hinge_core_b', 110),
  ('engine', 'w_hinge_core_c', 120),
  ('engine', 'w_squat_push_a', 100),
  ('engine', 'w_squat_push_b', 110),
  ('engine', 'w_squat_push_c', 120),
  ('engine', 'w_test', 80),
  ('dumbbells', 'w_bench_21_15_9', 150),
  ('dumbbells', 'w_bench_dt', 150),
  ('dumbbells', 'w_complex_a', 100),
  ('dumbbells', 'w_complex_b', 110),
  ('dumbbells', 'w_engine_amrap12', 100),
  ('dumbbells', 'w_engine_amrap15', 110),
  ('dumbbells', 'w_engine_emom12', 100),
  ('dumbbells', 'w_engine_tabata', 100),
  ('dumbbells', 'w_hinge_pull_a', 110),
  ('dumbbells', 'w_hinge_pull_b', 120),
  ('dumbbells', 'w_hinge_pull_c', 120),
  ('dumbbells', 'w_squat_press_a', 100),
  ('dumbbells', 'w_squat_press_b', 120),
  ('dumbbells', 'w_squat_press_c', 120),
  ('dumbbells', 'w_technique_flow', 90),
  ('dumbbells', 'w_test', 80),
  ('kettlebell', 'w_bench_swings_squats', 150),
  ('kettlebell', 'w_clean_press', 110),
  ('kettlebell', 'w_flow', 90),
  ('kettlebell', 'w_metcon_amrap15', 110),
  ('kettlebell', 'w_metcon_emom12', 100),
  ('kettlebell', 'w_metcon_ladder', 100),
  ('kettlebell', 'w_snatch_swing', 120),
  ('kettlebell', 'w_squat_press_a', 100),
  ('kettlebell', 'w_squat_press_b', 110),
  ('kettlebell', 'w_squat_press_c', 120),
  ('kettlebell', 'w_swing_school_a', 100),
  ('kettlebell', 'w_swing_school_b', 110),
  ('kettlebell', 'w_test', 80),
  ('athlete', 'w_bench_cindy', 150),
  ('athlete', 'w_bench_half_murph', 150),
  ('athlete', 'w_chipper_a', 110),
  ('athlete', 'w_chipper_b', 120),
  ('athlete', 'w_engine_amrap15', 110),
  ('athlete', 'w_engine_emom12', 100),
  ('athlete', 'w_engine_emom16', 110),
  ('athlete', 'w_engine_tabata', 100),
  ('athlete', 'w_murph_prep_a', 120),
  ('athlete', 'w_murph_prep_b', 130),
  ('athlete', 'w_pull_hinge_a', 110),
  ('athlete', 'w_pull_hinge_b', 120),
  ('athlete', 'w_pull_hinge_c', 120),
  ('athlete', 'w_skill_flow', 90),
  ('athlete', 'w_squat_push_a', 110),
  ('athlete', 'w_squat_push_b', 120),
  ('athlete', 'w_squat_push_c', 120),
  ('athlete', 'w_test', 80)
on conflict (course_id, id) do update set base_points = excluded.base_points;

-- Rows content no longer defines (workouts first: they reference courses).
delete from public.workouts where (course_id, id) not in (
  ('start', 'w_benchmark_four_rounds'),
  ('start', 'w_circuit_no_jump'),
  ('start', 'w_emom_12'),
  ('start', 'w_hinge_core_1'),
  ('start', 'w_hinge_core_2'),
  ('start', 'w_hinge_core_3'),
  ('start', 'w_hinge_core_4'),
  ('start', 'w_squat_push_1'),
  ('start', 'w_squat_push_2'),
  ('start', 'w_squat_push_3'),
  ('start', 'w_squat_push_4'),
  ('start', 'w_test_start'),
  ('engine', 'w_bench_burpees'),
  ('engine', 'w_bench_cindy'),
  ('engine', 'w_chipper_a'),
  ('engine', 'w_chipper_b'),
  ('engine', 'w_easy_flow'),
  ('engine', 'w_engine_amrap10'),
  ('engine', 'w_engine_amrap15'),
  ('engine', 'w_engine_emom12'),
  ('engine', 'w_engine_tabata'),
  ('engine', 'w_hinge_core_a'),
  ('engine', 'w_hinge_core_b'),
  ('engine', 'w_hinge_core_c'),
  ('engine', 'w_squat_push_a'),
  ('engine', 'w_squat_push_b'),
  ('engine', 'w_squat_push_c'),
  ('engine', 'w_test'),
  ('dumbbells', 'w_bench_21_15_9'),
  ('dumbbells', 'w_bench_dt'),
  ('dumbbells', 'w_complex_a'),
  ('dumbbells', 'w_complex_b'),
  ('dumbbells', 'w_engine_amrap12'),
  ('dumbbells', 'w_engine_amrap15'),
  ('dumbbells', 'w_engine_emom12'),
  ('dumbbells', 'w_engine_tabata'),
  ('dumbbells', 'w_hinge_pull_a'),
  ('dumbbells', 'w_hinge_pull_b'),
  ('dumbbells', 'w_hinge_pull_c'),
  ('dumbbells', 'w_squat_press_a'),
  ('dumbbells', 'w_squat_press_b'),
  ('dumbbells', 'w_squat_press_c'),
  ('dumbbells', 'w_technique_flow'),
  ('dumbbells', 'w_test'),
  ('kettlebell', 'w_bench_swings_squats'),
  ('kettlebell', 'w_clean_press'),
  ('kettlebell', 'w_flow'),
  ('kettlebell', 'w_metcon_amrap15'),
  ('kettlebell', 'w_metcon_emom12'),
  ('kettlebell', 'w_metcon_ladder'),
  ('kettlebell', 'w_snatch_swing'),
  ('kettlebell', 'w_squat_press_a'),
  ('kettlebell', 'w_squat_press_b'),
  ('kettlebell', 'w_squat_press_c'),
  ('kettlebell', 'w_swing_school_a'),
  ('kettlebell', 'w_swing_school_b'),
  ('kettlebell', 'w_test'),
  ('athlete', 'w_bench_cindy'),
  ('athlete', 'w_bench_half_murph'),
  ('athlete', 'w_chipper_a'),
  ('athlete', 'w_chipper_b'),
  ('athlete', 'w_engine_amrap15'),
  ('athlete', 'w_engine_emom12'),
  ('athlete', 'w_engine_emom16'),
  ('athlete', 'w_engine_tabata'),
  ('athlete', 'w_murph_prep_a'),
  ('athlete', 'w_murph_prep_b'),
  ('athlete', 'w_pull_hinge_a'),
  ('athlete', 'w_pull_hinge_b'),
  ('athlete', 'w_pull_hinge_c'),
  ('athlete', 'w_skill_flow'),
  ('athlete', 'w_squat_push_a'),
  ('athlete', 'w_squat_push_b'),
  ('athlete', 'w_squat_push_c'),
  ('athlete', 'w_test')
);
delete from public.courses where id not in ('start', 'engine', 'dumbbells', 'kettlebell', 'athlete');

-- =============================================================================
-- 0005_subscriptions.sql — monthly / annual subscriptions and the entitlements union
-- =============================================================================

-- =============================================================================
-- 0005 — Subscriptions: monthly / annual access to every course.
--
-- A subscription is keyed by email like a purchase, one row per email: a customer either has a
-- subscription or does not, and renewals extend the same row. Access is time-boxed
-- (`expires_at`), which is the whole difference from a purchase — nothing else in the schema
-- changes: `my_entitlements` simply lists every course while the subscription is live, so the
-- app, the leaderboard and the storage policies keep working on course ids.
-- "Live" is one function, subscription_live(): active or cancelled, and the paid period not over.
--
-- Writers, in order of trust:
--   create_subscription_order()   anonymous visitor → a pending intent (email ↔ plan)
--   apply_subscription_payment()  the payment webhook (service role) → activate / extend
--   admin_set_subscription()      the coach → grant, extend, cancel by hand
-- Customers never write the table and read it only through `my_subscription`.
-- =============================================================================

create table if not exists public.subscriptions (
  id           uuid primary key default gen_random_uuid(),
  email        citext not null unique,
  plan         text not null check (plan in ('monthly', 'annual')),
  status       text not null default 'pending' check (status in ('pending', 'active', 'cancelled')),
  -- Access is live while status = 'active' and now() < expires_at. A cancelled subscription keeps
  -- its expires_at: the customer paid for that period and keeps it.
  started_at   timestamptz,
  expires_at   timestamptz,
  -- 'landing' / 'app' for intents, 'prodamus' for webhook payments, 'admin' for manual grants.
  source       text,
  -- The provider's own subscription / order id, for support and for idempotent webhooks.
  provider_ref text,
  locale       text,
  note         text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

comment on table public.subscriptions is
  'Monthly / annual access to every course. pending → active (payment) → cancelled; access ends at expires_at.';

alter table public.subscriptions drop constraint if exists subscriptions_email_len;
alter table public.subscriptions add constraint subscriptions_email_len
  check (length(email::text) <= 254) not valid;
alter table public.subscriptions drop constraint if exists subscriptions_source_len;
alter table public.subscriptions add constraint subscriptions_source_len
  check (source is null or length(source) <= 40) not valid;
alter table public.subscriptions drop constraint if exists subscriptions_provider_ref_len;
alter table public.subscriptions add constraint subscriptions_provider_ref_len
  check (provider_ref is null or length(provider_ref) <= 120) not valid;
alter table public.subscriptions drop constraint if exists subscriptions_locale_fmt;
alter table public.subscriptions add constraint subscriptions_locale_fmt
  check (locale is null or locale in ('ru', 'en')) not valid;
alter table public.subscriptions drop constraint if exists subscriptions_note_len;
alter table public.subscriptions add constraint subscriptions_note_len
  check (note is null or length(note) <= 500) not valid;

create index if not exists subscriptions_status_created_idx on public.subscriptions (status, created_at desc);

drop trigger if exists subscriptions_touch on public.subscriptions;
create trigger subscriptions_touch
  before update on public.subscriptions
  for each row execute function public.set_updated_at();

alter table public.subscriptions enable row level security;

-- Same access model as purchases: admins read and write through the API, customers see only
-- the `my_subscription` view (no note, no provider reference).
drop policy if exists "subscriptions: admins all" on public.subscriptions;
create policy "subscriptions: admins all"
  on public.subscriptions for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

revoke all on public.subscriptions from anon, authenticated;
grant select, insert, update, delete on public.subscriptions to authenticated;

-- -----------------------------------------------------------------------------
-- subscription_live — the one definition of "has access": the paid period is not over.
-- A cancelled subscription is live until its expires_at — cancelling stops renewals, it never
-- takes away time that was paid for. Pending never is.
-- -----------------------------------------------------------------------------
create or replace function public.subscription_live(p_status text, p_expires_at timestamptz)
returns boolean
language sql
stable
as $$
  select p_status in ('active', 'cancelled') and p_expires_at is not null and p_expires_at > now();
$$;

-- Views check function rights against the caller, so the predicate must be executable by users.
revoke execute on function public.subscription_live(text, timestamptz) from public, anon;
grant execute on function public.subscription_live(text, timestamptz) to authenticated;

-- -----------------------------------------------------------------------------
-- subscription_period — how long one payment buys.
-- -----------------------------------------------------------------------------
create or replace function public.subscription_period(p_plan text)
returns interval
language sql
immutable
as $$
  select case p_plan when 'annual' then interval '1 year' else interval '1 month' end;
$$;

revoke execute on function public.subscription_period(text) from public, anon, authenticated;

-- -----------------------------------------------------------------------------
-- my_subscription — the signed-in user's own row, without the coach's fields.
-- -----------------------------------------------------------------------------
drop view if exists public.my_subscription;
create view public.my_subscription
with (security_invoker = false)
as
  select s.plan, s.status, s.started_at, s.expires_at,
         public.subscription_live(s.status, s.expires_at) as is_live
  from public.subscriptions s
  where s.email = public.current_email();

revoke all on public.my_subscription from anon, authenticated;
grant select on public.my_subscription to authenticated;

-- -----------------------------------------------------------------------------
-- my_entitlements — purchased courses, plus every course while a subscription is live.
-- Replaces the view from 0002; the column list is unchanged so the client needs no change.
-- -----------------------------------------------------------------------------
drop view if exists public.my_entitlements;
create view public.my_entitlements
with (security_invoker = false)
as
  select p.course_id, p.activated_at
  from public.purchases p
  where p.status = 'active'
    and p.email = public.current_email()
  union
  select c.id as course_id, s.started_at as activated_at
  from public.subscriptions s
  cross join public.courses c
  where public.subscription_live(s.status, s.expires_at)
    and s.email = public.current_email();

revoke all on public.my_entitlements from anon, authenticated;
grant select on public.my_entitlements to authenticated;

-- -----------------------------------------------------------------------------
-- create_subscription_order — the landing / app "subscribe" form. Anonymous.
-- Records the intent so the payment can be matched to an email; never grants access.
-- Reuses the pending-order throttle of create_order() through the same table of buckets.
-- -----------------------------------------------------------------------------
create or replace function public.create_subscription_order(
  p_email  text,
  p_plan   text,
  p_locale text default 'ru',
  p_source text default 'landing'
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_email  citext;
  v_locale text;
  v_source text;
  v_id     uuid;
begin
  v_email := public.normalize_email(p_email);

  if p_plan is null or p_plan not in ('monthly', 'annual') then
    raise exception 'invalid_plan' using errcode = 'P0001', hint = 'monthly or annual';
  end if;

  v_locale := case when p_locale in ('ru', 'en') then p_locale else 'ru' end;
  v_source := left(coalesce(nullif(trim(p_source), ''), 'landing'), 40);

  -- One pending intent per email is enough; a live subscription is never downgraded by a form.
  insert into public.subscriptions (email, plan, status, source, locale)
  values (v_email, p_plan, 'pending', v_source, v_locale)
  on conflict (email) do update
    set plan       = case when public.subscription_live(subscriptions.status, subscriptions.expires_at)
                          then subscriptions.plan else excluded.plan end,
        source     = case when public.subscription_live(subscriptions.status, subscriptions.expires_at)
                          then subscriptions.source else excluded.source end,
        locale     = coalesce(excluded.locale, subscriptions.locale),
        updated_at = now()
  returning id into v_id;

  return v_id;
end;
$$;

revoke execute on function public.create_subscription_order(text, text, text, text) from public;
grant execute on function public.create_subscription_order(text, text, text, text) to anon, authenticated;

-- -----------------------------------------------------------------------------
-- apply_subscription_payment — called by the payment webhook with the service role.
-- Idempotent per provider reference: the same notification delivered twice extends once.
-- A payment while the subscription is still live extends from expires_at (a renewal);
-- after a gap it starts from now (a return), so nobody is charged for months they were away.
-- -----------------------------------------------------------------------------
create or replace function public.apply_subscription_payment(
  p_email        text,
  p_plan         text,
  p_provider_ref text default null,
  p_paid_at      timestamptz default now()
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_email  citext;
  v_row    public.subscriptions%rowtype;
  v_from   timestamptz;
  v_ref    text;
  v_id     uuid;
begin
  -- Only the service role (the webhook) and the SQL editor: never a signed-in user.
  if coalesce(current_setting('request.jwt.claims', true), '') <> ''
     and coalesce(current_setting('request.jwt.claims', true)::json ->> 'role', '') <> 'service_role' then
    raise exception 'not_allowed' using errcode = '42501';
  end if;

  v_email := public.normalize_email(p_email);
  if p_plan is null or p_plan not in ('monthly', 'annual') then
    raise exception 'invalid_plan' using errcode = 'P0001';
  end if;
  v_ref := left(nullif(trim(p_provider_ref), ''), 120);

  select * into v_row from public.subscriptions where email = v_email;

  if found and v_ref is not null and v_row.provider_ref = v_ref then
    return v_row.id; -- the same payment, delivered again
  end if;

  v_from := case
    when found and v_row.status in ('active', 'cancelled') and v_row.expires_at > p_paid_at then v_row.expires_at
    else p_paid_at
  end;

  insert into public.subscriptions (email, plan, status, started_at, expires_at, source, provider_ref)
  values (v_email, p_plan, 'active', p_paid_at, v_from + public.subscription_period(p_plan), 'prodamus', v_ref)
  on conflict (email) do update
    set plan         = excluded.plan,
        status       = 'active',
        started_at   = coalesce(subscriptions.started_at, excluded.started_at),
        expires_at   = excluded.expires_at,
        source       = 'prodamus',
        provider_ref = coalesce(excluded.provider_ref, subscriptions.provider_ref),
        updated_at   = now()
  returning id into v_id;

  return v_id;
end;
$$;

revoke execute on function public.apply_subscription_payment(text, text, text, timestamptz) from public, anon, authenticated;
grant execute on function public.apply_subscription_payment(text, text, text, timestamptz) to service_role;

-- -----------------------------------------------------------------------------
-- admin_set_subscription — grant, extend or cancel by hand (bank transfer, gift, support).
--   p_status 'active'    → expires_at = p_expires_at, or one period from now / from the current
--                          expiry when it is still in the future (an extension)
--   p_status 'cancelled' → access ends at the current expires_at (or now, if none)
-- -----------------------------------------------------------------------------
create or replace function public.admin_set_subscription(
  p_email      text,
  p_plan       text,
  p_status     text,
  p_expires_at timestamptz default null,
  p_note       text default null
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_email   citext;
  v_row     public.subscriptions%rowtype;
  v_expires timestamptz;
  v_id      uuid;
begin
  if not public.is_admin() then
    raise exception 'not_admin' using errcode = '42501';
  end if;

  v_email := public.normalize_email(p_email);
  if p_plan is null or p_plan not in ('monthly', 'annual') then
    raise exception 'invalid_plan' using errcode = 'P0001';
  end if;
  if p_status is null or p_status not in ('active', 'cancelled') then
    raise exception 'invalid_status' using errcode = 'P0001';
  end if;

  select * into v_row from public.subscriptions where email = v_email;

  if p_status = 'active' then
    v_expires := coalesce(
      p_expires_at,
      (case when found and public.subscription_live(v_row.status, v_row.expires_at) then v_row.expires_at else now() end)
        + public.subscription_period(p_plan)
    );
  else
    if not found then
      raise exception 'not_found' using errcode = 'P0002';
    end if;
    v_expires := coalesce(v_row.expires_at, now());
  end if;

  insert into public.subscriptions (email, plan, status, started_at, expires_at, source, note)
  values (v_email, p_plan, p_status, now(), v_expires, 'admin', left(nullif(trim(p_note), ''), 500))
  on conflict (email) do update
    set plan       = excluded.plan,
        status     = excluded.status,
        started_at = coalesce(subscriptions.started_at, excluded.started_at),
        expires_at = excluded.expires_at,
        source     = 'admin',
        note       = coalesce(excluded.note, subscriptions.note),
        updated_at = now()
  returning id into v_id;

  return v_id;
end;
$$;

revoke execute on function public.admin_set_subscription(text, text, text, timestamptz, text) from public, anon;
grant execute on function public.admin_set_subscription(text, text, text, timestamptz, text) to authenticated;

-- =============================================================================
-- Admin access — EDIT THIS BEFORE RUNNING
--
-- Replace the address with the one the coach will sign in with. Case does not matter (the column
-- is citext). Add a line per person who needs the admin screen.
-- =============================================================================

insert into public.admins (email) values ('CHANGE-ME@example.com')
on conflict (email) do nothing;
