/**
 * Exercise library, file C: light home equipment — pull-up bar, resistance bands, jump rope,
 * dumbbells and kettlebell. Ids, animation ids, units, equipment and levels are referenced by
 * courses and animations — keep them stable. Copy is shown in the workout player and on the
 * public /exercises/<slug>/ pages.
 */
import type { ExerciseInput } from '@/content/schema';

export const EXERCISES_C: ExerciseInput[] = [
  {
    id: 'pull_up',
    slug: { ru: 'podtyagivaniya', en: 'pull-up' },
    name: { ru: 'Подтягивания', en: 'Pull-up' },
    shortName: { ru: 'Подтягивания', en: 'Pull-up' },
    description: {
      ru: 'Подтягивания — главная вертикальная тяга в домашнем тренинге и лучший тест силы спины и хвата. Они строят широчайшие, бицепсы и мышцы между лопатками, которые в отжиманиях и жимах не работают, и уравновешивают всю жимовую нагрузку программы. Мы считаем строгие подтягивания: без раскачки, из полного виса до подбородка над перекладиной. Если чистых повторений пока нет — начни с негативных подтягиваний и виса.',
      en: 'The pull-up is the main vertical pull in home training and the best test of back and grip strength. It builds the lats, biceps and the muscles between the shoulder blades that push-ups and presses never touch, balancing all the pressing in the program. We count strict pull-ups: no kipping, from a full hang to chin over the bar. If you have no clean reps yet, start with negatives and dead hangs.',
    },
    howTo: [
      {
        ru: 'Возьмись за перекладину хватом сверху чуть шире плеч и повисни на прямых руках, ноги вместе или слегка скрещены.',
        en: 'Grip the bar overhand slightly wider than your shoulders and hang with straight arms, legs together or lightly crossed.',
      },
      {
        ru: 'Опусти плечи от ушей и сведи лопатки — движение начинается со спины, а не с локтей.',
        en: 'Pull your shoulders down away from your ears and set the shoulder blades — the movement starts from the back, not the elbows.',
      },
      {
        ru: 'Тяни локти вниз и назад, поднимая грудь к перекладине, пока подбородок не окажется над ней.',
        en: 'Drive your elbows down and back, bringing your chest toward the bar until your chin clears it.',
      },
      {
        ru: 'Плавно опустись до полного выпрямления рук — только после этого начинается следующее повторение.',
        en: 'Lower under control to fully straight arms — only then does the next rep begin.',
      },
    ],
    cues: [
      { ru: 'Локти вниз и назад', en: 'Elbows down and back' },
      { ru: 'Грудь к перекладине', en: 'Chest to the bar' },
      { ru: 'Пресс напряжён, ноги не качаются', en: 'Brace the abs, legs still' },
      { ru: 'Внизу — полный вис', en: 'Full hang at the bottom' },
    ],
    mistakes: [
      { ru: 'Раскачка и рывок ногами', en: 'Kipping and kicking with the legs' },
      {
        ru: 'Неполная амплитуда — руки не выпрямляются внизу',
        en: 'Half reps: arms never straighten at the bottom',
      },
      { ru: 'Подбородок тянется вверх, плечи уходят к ушам', en: 'Chin reaching up while the shoulders shrug' },
    ],
    breathing: {
      ru: 'Выдох на подъёме, вдох при опускании.',
      en: 'Exhale as you pull up, inhale as you lower.',
    },
    muscles: ['lats', 'biceps', 'back', 'core'],
    pattern: 'pull_vertical',
    equipment: ['pullup_bar'],
    level: 3,
    unit: 'reps',
    secondsPerRep: 3.0,
    met: 8.0,
    loadable: false,
    scaling: { easier: 'negative_pull_up' },
    animation: 'pull_up',
    tags: ['upper', 'pull', 'benchmark'],
  },
  {
    id: 'negative_pull_up',
    slug: { ru: 'negativnye-podtyagivaniya', en: 'negative-pull-up' },
    name: { ru: 'Негативные подтягивания', en: 'Negative pull-up' },
    shortName: { ru: 'Негативные', en: 'Negatives' },
    description: {
      ru: 'Негативные подтягивания — это только опускание: ты запрыгиваешь или залезаешь в верхнюю точку и медленно опускаешься в вис. Мышцы сильнее на удлинении, чем на сокращении, поэтому даже без единого подтягивания ты можешь нагрузить спину и бицепсы в полной амплитуде. Это самый короткий путь к первому чистому подтягиванию. Опускайся не быстрее трёх секунд — иначе пользы почти нет.',
      en: 'Negative pull-ups are the lowering half only: you jump or climb to the top position and lower yourself slowly into a hang. Muscles are stronger while lengthening than while shortening, so even with zero pull-ups you can load your back and biceps through the full range. It is the shortest road to your first strict pull-up. Take at least three seconds to lower — faster than that and there is little benefit.',
    },
    howTo: [
      {
        ru: 'Встань под перекладиной на стул или подпрыгни и займи верхнее положение: подбородок над перекладиной, хват сверху чуть шире плеч.',
        en: 'Use a chair or a jump to get into the top position: chin over the bar, overhand grip slightly wider than your shoulders.',
      },
      {
        ru: 'Сведи лопатки, напряги пресс и убери ноги с опоры — держи вес на руках.',
        en: 'Set your shoulder blades, brace your abs and take your feet off the support so your arms carry the weight.',
      },
      {
        ru: 'Медленно опускайся 3–5 секунд, сопротивляясь всей спиной, пока руки полностью не выпрямятся.',
        en: 'Lower yourself over 3–5 seconds, resisting with the whole back, until your arms are fully straight.',
      },
      {
        ru: 'Отпусти перекладину или встань на опору, снова поднимись наверх и повтори.',
        en: 'Step off or drop down, get back to the top and repeat.',
      },
    ],
    cues: [
      { ru: 'Считай до трёх на опускании', en: 'Count to three on the way down' },
      { ru: 'Лопатки вместе', en: 'Shoulder blades together' },
      { ru: 'Тормози до самого низа', en: 'Brake all the way to the bottom' },
    ],
    mistakes: [
      { ru: 'Падение вниз без контроля', en: 'Dropping instead of lowering' },
      {
        ru: 'Отпускание в середине пути, до полного виса',
        en: 'Letting go halfway before reaching a full hang',
      },
      { ru: 'Плечи задраны к ушам', en: 'Shoulders shrugged up to the ears' },
    ],
    breathing: {
      ru: 'Вдох наверху, длинный выдох, пока опускаешься.',
      en: 'Inhale at the top, long exhale as you lower.',
    },
    muscles: ['lats', 'biceps', 'back', 'core'],
    pattern: 'pull_vertical',
    equipment: ['pullup_bar'],
    level: 2,
    unit: 'reps',
    secondsPerRep: 5.0,
    met: 6.0,
    loadable: false,
    scaling: { easier: 'dead_hang', harder: 'pull_up' },
    animation: 'negative_pull_up',
    tags: ['upper', 'pull'],
  },
  {
    id: 'dead_hang',
    slug: { ru: 'vis-na-perekladine', en: 'dead-hang' },
    name: { ru: 'Вис на перекладине', en: 'Dead hang' },
    shortName: { ru: 'Вис', en: 'Dead hang' },
    description: {
      ru: 'Вис на перекладине — простое удержание собственного веса на прямых руках. Он тренирует хват и предплечья, растягивает широчайшие и плечи и разгружает позвоночник после приседаний и тяг. Для новичка это первая ступень к подтягиваниям: пока хват не держит хотя бы 30 секунд, тянуться наверх рано. Ещё вис — отличная заминка для плеч в конце тренировки.',
      en: 'The dead hang is simply holding your body weight on straight arms. It trains grip and forearms, stretches the lats and shoulders and decompresses the spine after squats and deadlifts. For a beginner it is the first step toward pull-ups: until your grip holds for at least 30 seconds, pulling up can wait. It also makes a great shoulder cool-down at the end of a session.',
    },
    howTo: [
      {
        ru: 'Возьмись за перекладину хватом сверху на ширине плеч, большие пальцы обхватывают перекладину.',
        en: 'Grip the bar overhand at shoulder width, thumbs wrapped around the bar.',
      },
      {
        ru: 'Повисни на прямых руках, ноги вместе, стопы не касаются пола.',
        en: 'Hang with straight arms, legs together, feet off the floor.',
      },
      {
        ru: 'Слегка опусти плечи от ушей и напряги пресс, чтобы тело не раскачивалось.',
        en: 'Draw your shoulders slightly down from your ears and brace your abs so the body does not swing.',
      },
      {
        ru: 'Держи заданное время, дыши спокойно, затем плавно встань на пол.',
        en: 'Hold for the prescribed time, breathing calmly, then step down under control.',
      },
    ],
    cues: [
      { ru: 'Сожми перекладину', en: 'Squeeze the bar' },
      { ru: 'Тело спокойно, без качания', en: 'Body quiet, no swinging' },
      { ru: 'Дыши ровно', en: 'Keep breathing' },
    ],
    mistakes: [
      { ru: 'Хват без большого пальца', en: 'Thumbless grip' },
      { ru: 'Раскачивание и дёрганье ногами', en: 'Swinging and kicking the legs' },
      { ru: 'Задержка дыхания', en: 'Holding your breath' },
    ],
    breathing: {
      ru: 'Спокойное ровное дыхание животом.',
      en: 'Calm, even belly breathing.',
    },
    muscles: ['lats', 'back', 'shoulders', 'core'],
    pattern: 'pull_vertical',
    equipment: ['pullup_bar'],
    level: 1,
    unit: 'seconds',
    met: 3.0,
    loadable: false,
    scaling: { harder: 'negative_pull_up' },
    animation: 'dead_hang',
    tags: ['upper', 'pull', 'cooldown'],
  },
  {
    id: 'hanging_knee_raise',
    slug: { ru: 'podem-koleney-v-vise', en: 'hanging-knee-raise' },
    name: { ru: 'Подъём коленей в висе', en: 'Hanging knee raise' },
    shortName: { ru: 'Колени в висе', en: 'Knee raise' },
    description: {
      ru: 'Подъём коленей в висе — упражнение на пресс, которое заодно тренирует хват и стабильность плеч. Вися на перекладине, ты подтягиваешь колени к груди, скручивая таз вверх, а не просто размахивая ногами. Это следующий шаг после подъёмов ног лёжа и подводка к подъёмам прямых ног, «носки к перекладине» и другим гимнастическим элементам.',
      en: 'The hanging knee raise is an abs exercise that also trains your grip and shoulder stability. Hanging from the bar, you pull your knees toward your chest by curling the pelvis up rather than swinging the legs. It is the step after lying leg raises and the lead-in to straight-leg raises, toes-to-bar and other gymnastics skills.',
    },
    howTo: [
      {
        ru: 'Повисни на перекладине хватом сверху, руки прямые, плечи слегка опущены, ноги вместе.',
        en: 'Hang from the bar with an overhand grip, arms straight, shoulders slightly drawn down, legs together.',
      },
      {
        ru: 'Напряги пресс и подтяни колени к груди, подкручивая таз вверх — поясница округляется, а не прогибается.',
        en: 'Brace your abs and draw your knees toward your chest, curling the pelvis up — the lower back rounds rather than arches.',
      },
      {
        ru: 'Задержись на секунду наверху: колени выше уровня таза.',
        en: 'Pause for a second at the top with your knees above hip height.',
      },
      {
        ru: 'Медленно опусти ноги в исходный вис без раскачки и повтори.',
        en: 'Lower your legs slowly back to the hang without swinging and repeat.',
      },
    ],
    cues: [
      { ru: 'Таз подкручивай вверх', en: 'Curl the pelvis up' },
      { ru: 'Опускай медленно', en: 'Lower slowly' },
      { ru: 'Без раскачки', en: 'No swing' },
    ],
    mistakes: [
      { ru: 'Раскачивание для помощи ногам', en: 'Using a swing to help the legs up' },
      {
        ru: 'Колени поднимаются только за счёт сгибателей бедра, таз не скручивается',
        en: 'Lifting from the hip flexors only, with no pelvic curl',
      },
      { ru: 'Ноги падают вниз рывком', en: 'Legs dropping with a jerk' },
    ],
    breathing: {
      ru: 'Выдох на подъёме коленей, вдох при опускании.',
      en: 'Exhale as the knees come up, inhale as they lower.',
    },
    muscles: ['core', 'hip_flexors', 'lats', 'obliques'],
    pattern: 'core_flexion',
    equipment: ['pullup_bar'],
    level: 2,
    unit: 'reps',
    secondsPerRep: 2.5,
    met: 5.0,
    loadable: false,
    scaling: { easier: 'leg_raise' },
    animation: 'hanging_knee_raise',
    tags: ['core', 'upper'],
  },
  {
    id: 'band_row',
    slug: { ru: 'tyaga-rezinki-k-poyasu', en: 'band-row' },
    name: { ru: 'Тяга резинки к поясу', en: 'Band row' },
    shortName: { ru: 'Тяга резинки', en: 'Band row' },
    description: {
      ru: 'Тяга резинки к поясу — горизонтальная тяга для середины спины, задних дельт и бицепсов. Резинка даёт нагрузку, которая растёт к концу движения, поэтому именно в точке сведения лопаток спина работает сильнее всего. Мы используем её, чтобы уравновесить отжимания, и как замену тягам с гантелями, когда их нет. Закрепи резинку за устойчивую опору на уровне груди или зацепи за стопы сидя на полу.',
      en: 'The band row is a horizontal pull for the mid-back, rear shoulders and biceps. A band resists harder toward the end of the movement, so the back works hardest exactly where the shoulder blades squeeze together. We use it to balance push-ups and as a substitute for dumbbell rows when you have no weights. Anchor the band to something solid at chest height, or loop it around your feet while seated on the floor.',
    },
    howTo: [
      {
        ru: 'Закрепи резинку на уровне груди, встань лицом к опоре и отойди, пока резинка не натянется при вытянутых руках. Стопы на ширине таза, колени мягкие.',
        en: 'Anchor the band at chest height, face the anchor and step back until the band is taut with your arms extended. Feet hip-width apart, knees soft.',
      },
      {
        ru: 'Опусти плечи и тяни рукоятки к поясу, ведя локти вдоль корпуса назад.',
        en: 'Set your shoulders down and pull the handles toward your waist, driving the elbows back along your sides.',
      },
      {
        ru: 'В конечной точке сведи лопатки и задержись на секунду, корпус неподвижен.',
        en: 'At the end squeeze your shoulder blades together and hold for a second, torso still.',
      },
      {
        ru: 'Медленно верни руки вперёд, контролируя натяжение, и повтори.',
        en: 'Return your arms forward slowly, controlling the band tension, and repeat.',
      },
    ],
    cues: [
      { ru: 'Локти к поясу', en: 'Elbows to the waist' },
      { ru: 'Сведи лопатки', en: 'Squeeze the shoulder blades' },
      { ru: 'Корпус не качается', en: 'Torso stays still' },
    ],
    mistakes: [
      { ru: 'Плечи поднимаются к ушам', en: 'Shoulders shrugging toward the ears' },
      {
        ru: 'Корпус отклоняется назад, чтобы помочь рукам',
        en: 'Leaning back to help the arms',
      },
      { ru: 'Резинка бросается вперёд без контроля', en: 'Letting the band snap forward' },
    ],
    breathing: {
      ru: 'Выдох на тяге, вдох при возврате.',
      en: 'Exhale as you pull, inhale as you return.',
    },
    muscles: ['back', 'lats', 'biceps', 'shoulders'],
    pattern: 'pull_horizontal',
    equipment: ['bands'],
    level: 1,
    unit: 'reps',
    secondsPerRep: 2.0,
    met: 3.8,
    loadable: false,
    scaling: {},
    animation: 'band_row',
    tags: ['upper', 'pull'],
  },
  {
    id: 'band_pull_apart',
    slug: { ru: 'razvedenie-rezinki', en: 'band-pull-apart' },
    name: { ru: 'Разведение резинки', en: 'Band pull-apart' },
    shortName: { ru: 'Разведение', en: 'Pull-apart' },
    description: {
      ru: 'Разведение резинки — растягивание ленты перед собой прямыми руками. Упражнение будит задние дельты, ромбовидные и ротаторную манжету — мелкие мышцы, которые держат плечи в правильном положении и защищают их в отжиманиях и жимах над головой. Мы ставим его в разминку перед любой работой на верх тела и как «антидот» от сидения за компьютером.',
      en: 'The band pull-apart stretches a band across your chest with straight arms. It wakes up the rear delts, rhomboids and rotator cuff — the small muscles that hold your shoulders in position and protect them in push-ups and overhead presses. We put it in every upper-body warm-up and prescribe it as the antidote to a day at the desk.',
    },
    howTo: [
      {
        ru: 'Встань прямо, возьми резинку двумя руками хватом сверху на ширине плеч и вытяни руки перед собой на уровне груди.',
        en: 'Stand tall, hold the band overhand with hands shoulder-width apart and extend your arms in front of you at chest height.',
      },
      {
        ru: 'Разводи прямые руки в стороны, растягивая резинку, пока она не коснётся груди, — лопатки сходятся вместе.',
        en: 'Pull your straight arms apart, stretching the band until it touches your chest, shoulder blades squeezing together.',
      },
      {
        ru: 'Задержись на секунду, плечи опущены, рёбра не выпячиваются.',
        en: 'Hold for a second with your shoulders down and ribs tucked.',
      },
      {
        ru: 'Плавно верни руки вперёд, не давая резинке провиснуть, и повтори.',
        en: 'Return your arms forward under control without letting the band go slack, and repeat.',
      },
    ],
    cues: [
      { ru: 'Руки прямые', en: 'Arms straight' },
      { ru: 'Лопатки вместе', en: 'Shoulder blades together' },
      { ru: 'Плечи вниз', en: 'Shoulders down' },
    ],
    mistakes: [
      { ru: 'Локти сгибаются — работает бицепс, а не спина', en: 'Elbows bending so the biceps take over' },
      { ru: 'Плечи задираются к ушам', en: 'Shoulders creeping up to the ears' },
      { ru: 'Прогиб в пояснице и выпяченные рёбра', en: 'Arching the lower back and flaring the ribs' },
    ],
    breathing: {
      ru: 'Выдох на разведении, вдох на возврате.',
      en: 'Exhale as you pull apart, inhale as you return.',
    },
    muscles: ['shoulders', 'back'],
    pattern: 'pull_horizontal',
    equipment: ['bands'],
    level: 1,
    unit: 'reps',
    secondsPerRep: 2.0,
    met: 3.0,
    loadable: false,
    scaling: {},
    animation: 'band_pull_apart',
    tags: ['upper', 'pull', 'warmup', 'mobility'],
  },
  {
    id: 'single_under',
    slug: { ru: 'pryzhki-na-skakalke', en: 'single-unders' },
    name: { ru: 'Прыжки на скакалке', en: 'Single-unders' },
    shortName: { ru: 'Скакалка', en: 'Single-unders' },
    description: {
      ru: 'Прыжки на скакалке — один оборот троса на один прыжок. Это самое эффективное домашнее кардио: за минуту скакалка сжигает больше, чем бег в среднем темпе, и заодно тренирует икры, стопы, координацию и ритм. Мы используем её в разминке и как «дыхательный» элемент в метконах. Прыгай низко, приземляйся мягко, крути скакалку кистями, а не всей рукой.',
      en: 'Single-unders are one rope turn per jump. They are the most efficient home cardio there is: minute for minute the rope burns more than a moderate run while training the calves, feet, coordination and rhythm. We use them in warm-ups and as the breathing element in metcons. Jump low, land softly and turn the rope with your wrists, not your whole arms.',
    },
    howTo: [
      {
        ru: 'Подбери длину: встань на середину скакалки — рукоятки должны доходить до подмышек. Возьми рукоятки, локти прижаты к бокам, скакалка за пятками.',
        en: 'Check the length: standing on the middle of the rope, the handles should reach your armpits. Hold the handles with elbows tucked to your sides, rope resting behind your heels.',
      },
      {
        ru: 'Крути скакалку небольшими круговыми движениями кистей и перепрыгивай её обеими ногами на 3–5 см от пола.',
        en: 'Turn the rope with small circles of the wrists and hop over it with both feet, 3–5 cm off the floor.',
      },
      {
        ru: 'Приземляйся на переднюю часть стопы с мягкими коленями, корпус прямой, взгляд вперёд.',
        en: 'Land on the balls of your feet with soft knees, torso upright, eyes forward.',
      },
      {
        ru: 'Держи ровный ритм: один оборот — один прыжок, без лишних подскоков между оборотами.',
        en: 'Keep an even rhythm: one turn, one jump, with no extra bounce between turns.',
      },
    ],
    cues: [
      { ru: 'Крути кистями', en: 'Turn with the wrists' },
      { ru: 'Прыгай низко', en: 'Jump low' },
      { ru: 'Локти у корпуса', en: 'Elbows in' },
      { ru: 'Мягко на носки', en: 'Soft on the balls of the feet' },
    ],
    mistakes: [
      { ru: 'Слишком высокие прыжки с поджиманием ног', en: 'Jumping too high and tucking the legs' },
      { ru: 'Крутишь всей рукой от плеча', en: 'Turning the rope from the shoulders' },
      { ru: 'Приземление на всю стопу или на пятки', en: 'Landing flat-footed or on the heels' },
    ],
    breathing: {
      ru: 'Ровное дыхание в такт прыжкам — не задерживай воздух.',
      en: 'Steady breathing in time with the jumps; never hold your breath.',
    },
    muscles: ['calves', 'quads', 'shoulders', 'cardio'],
    pattern: 'jump',
    equipment: ['jump_rope'],
    level: 1,
    unit: 'reps',
    secondsPerRep: 0.6,
    met: 11.0,
    loadable: false,
    scaling: { easier: 'jumping_jack', harder: 'double_under' },
    animation: 'single_under',
    tags: ['cardio', 'warmup'],
  },
  {
    id: 'double_under',
    slug: { ru: 'dvoynye-pryzhki-na-skakalke', en: 'double-unders' },
    name: { ru: 'Двойные прыжки на скакалке', en: 'Double-unders' },
    shortName: { ru: 'Двойные', en: 'Double-unders' },
    description: {
      ru: 'Двойные прыжки — два оборота скакалки за один прыжок. Это классический навык кроссфита: он требует быстрых кистей, чуть более высокого прыжка и, главное, спокойствия — как только ты начинаешь дёргаться, скакалка бьёт по ногам. Двойные разгоняют пульс сильнее любого другого упражнения без веса и учат тело работать расслабленно на высокой скорости. Осваивай их, когда одинарные идут без сбоев минуту подряд.',
      en: 'Double-unders are two rope turns per jump. A classic CrossFit skill: they need fast wrists, a slightly higher jump and, above all, calm — the moment you tense up the rope whips your legs. Doubles push your heart rate higher than any other unloaded movement and teach your body to stay relaxed at speed. Learn them once you can do single-unders for a minute without a miss.',
    },
    howTo: [
      {
        ru: 'Начни с нескольких одинарных прыжков в ровном ритме, локти у корпуса, кисти крутят скакалку.',
        en: 'Start with a few single-unders at an even rhythm, elbows in, wrists turning the rope.',
      },
      {
        ru: 'Прыгни чуть выше обычного и в воздухе резко ускорь кисти, чтобы скакалка прошла под ногами дважды.',
        en: 'Jump a little higher than usual and snap your wrists faster in the air so the rope passes under you twice.',
      },
      {
        ru: 'Тело остаётся вертикальным и вытянутым, ноги вместе и прямые, — не поджимай колени и не складывайся.',
        en: 'Keep your body tall and straight, legs together and extended — do not tuck the knees or pike at the hips.',
      },
      {
        ru: 'Приземлись мягко на носки и продолжай: либо каждый прыжок двойной, либо чередуй с одинарными, пока учишься.',
        en: 'Land softly on the balls of your feet and keep going: every jump a double, or alternate with singles while you are learning.',
      },
    ],
    cues: [
      { ru: 'Быстрые кисти, а не высокий прыжок', en: 'Fast wrists, not a high jump' },
      { ru: 'Тело вытянуто в струну', en: 'Body tall and straight' },
      { ru: 'Расслабь плечи', en: 'Relax the shoulders' },
    ],
    mistakes: [
      { ru: 'Поджимание коленей и «лягушка» в воздухе', en: 'Tucking the knees into a frog jump' },
      { ru: 'Руки уходят в стороны, скакалка становится короткой', en: 'Arms drifting wide so the rope gets too short' },
      { ru: 'Каждый прыжок «на пределе» — нет ритма', en: 'Every jump at max effort with no rhythm' },
    ],
    breathing: {
      ru: 'Дыши ритмично и не задерживай дыхание на высокой скорости.',
      en: 'Breathe rhythmically and never hold your breath at speed.',
    },
    muscles: ['calves', 'quads', 'shoulders', 'core', 'cardio'],
    pattern: 'jump',
    equipment: ['jump_rope'],
    level: 3,
    unit: 'reps',
    secondsPerRep: 0.8,
    met: 12.0,
    loadable: false,
    scaling: { easier: 'single_under' },
    animation: 'double_under',
    tags: ['cardio', 'explosive', 'benchmark'],
  },
  {
    id: 'db_goblet_squat',
    slug: { ru: 'goblet-prised-s-gantelyu', en: 'goblet-squat' },
    name: { ru: 'Гоблет-присед с гантелью', en: 'Goblet squat' },
    shortName: { ru: 'Гоблет-присед', en: 'Goblet squat' },
    description: {
      ru: 'Гоблет-присед — приседание с гантелью, прижатой к груди обеими руками, как кубок. Вес перед корпусом сам выставляет технику: заставляет держать грудь вверх, садиться между коленей и не заваливаться вперёд. Это первое приседание с отягощением в программе и лучший способ научиться приседать глубоко и чисто. Одной гантели достаточно — держи её за верхний диск вертикально.',
      en: 'The goblet squat is a squat with a dumbbell held against your chest in both hands, like a goblet. The weight in front of your body coaches the technique for you: it keeps the chest up, makes you sit down between your knees and stops you from folding forward. It is the first loaded squat in the program and the best way to learn to squat deep and clean. One dumbbell is enough — hold it vertically by the top plate.',
    },
    howTo: [
      {
        ru: 'Возьми гантель вертикально за верхний диск и прижми к груди, локти смотрят вниз. Стопы на ширине плеч, носки слегка наружу.',
        en: 'Hold the dumbbell vertically by the top plate against your chest, elbows pointing down. Feet shoulder-width apart, toes slightly out.',
      },
      {
        ru: 'Отведи таз назад и садись вниз, разводя колени по направлению носков; гантель остаётся прижатой к груди.',
        en: 'Push your hips back and sit down, knees tracking over your toes; the dumbbell stays glued to your chest.',
      },
      {
        ru: 'Опустись, пока бёдра не будут параллельны полу или ниже, локти проходят между коленей, спина прямая.',
        en: 'Descend until your thighs are parallel to the floor or lower, elbows passing between your knees, back flat.',
      },
      {
        ru: 'Оттолкнись всей стопой и встань, полностью выпрямив колени и сжав ягодицы.',
        en: 'Drive through the whole foot and stand up, fully extending the knees and squeezing the glutes.',
      },
    ],
    cues: [
      { ru: 'Гантель к груди', en: 'Dumbbell to the chest' },
      { ru: 'Локти между коленей', en: 'Elbows between the knees' },
      { ru: 'Грудь вверх', en: 'Chest up' },
      { ru: 'Пятки на полу', en: 'Heels down' },
    ],
    mistakes: [
      { ru: 'Гантель отходит от груди — плечи и спина устают раньше ног', en: 'Dumbbell drifting away from the chest so the shoulders and back tire before the legs' },
      { ru: 'Колени сваливаются внутрь', en: 'Knees caving inward' },
      { ru: 'Спина округляется в нижней точке', en: 'Back rounding at the bottom' },
    ],
    breathing: {
      ru: 'Вдох перед приседом, задержи на опускании, выдох на подъёме.',
      en: 'Inhale before the squat, hold on the way down, exhale as you stand.',
    },
    muscles: ['quads', 'glutes', 'core', 'back'],
    pattern: 'squat',
    equipment: ['dumbbells'],
    level: 1,
    unit: 'reps',
    secondsPerRep: 3.0,
    met: 6.0,
    loadable: true,
    scaling: { easier: 'air_squat', harder: 'db_front_squat' },
    animation: 'goblet_squat',
    tags: ['lower'],
  },
  {
    id: 'db_front_squat',
    slug: { ru: 'frontalnyy-prised-s-gantelyami', en: 'dumbbell-front-squat' },
    name: { ru: 'Фронтальный присед с гантелями', en: 'Dumbbell front squat' },
    shortName: { ru: 'Фронтальный присед', en: 'Front squat' },
    description: {
      ru: 'Фронтальный присед с гантелями — приседание с двумя гантелями на плечах. Вес вдвое больше, чем в гоблет-приседе, и держать его нужно локтями вверх, поэтому корпус и верх спины работают почти так же, как ноги. Это главное силовое приседание курса с гантелями и половина трастера: освоив его, ты готов соединить присед с жимом.',
      en: 'The dumbbell front squat is a squat with two dumbbells resting on your shoulders. You carry twice the load of a goblet squat and have to hold it with the elbows up, so the trunk and upper back work almost as hard as the legs. It is the main strength squat of the dumbbell course and one half of the thruster: once you own it, you are ready to link squat and press.',
    },
    howTo: [
      {
        ru: 'Подними гантели на плечи: одна головка гантели лежит на плече, локти направлены вперёд и вверх. Стопы на ширине плеч, носки чуть наружу.',
        en: 'Bring the dumbbells to your shoulders with one head of each dumbbell resting on the shoulder, elbows pointing forward and up. Feet shoulder-width apart, toes slightly out.',
      },
      {
        ru: 'Напряги пресс, отведи таз назад и садись вниз, колени идут по направлению носков.',
        en: 'Brace your abs, push your hips back and sit down, knees tracking over your toes.',
      },
      {
        ru: 'Опустись до параллели бёдер с полом или ниже, локти всё время смотрят вперёд, корпус вертикален.',
        en: 'Descend to parallel or below, elbows still pointing forward, torso upright.',
      },
      {
        ru: 'Оттолкнись всей стопой и встань, полностью разгибая колени и бёдра.',
        en: 'Drive through the whole foot and stand, fully extending knees and hips.',
      },
    ],
    cues: [
      { ru: 'Локти вверх', en: 'Elbows up' },
      { ru: 'Корпус вертикально', en: 'Torso upright' },
      { ru: 'Колени в стороны', en: 'Knees out' },
    ],
    mistakes: [
      { ru: 'Локти падают, гантели скатываются вперёд', en: 'Elbows dropping so the dumbbells roll forward' },
      { ru: 'Наклон корпуса вперёд в нижней точке', en: 'Torso folding forward at the bottom' },
      { ru: 'Пятки отрываются от пола', en: 'Heels lifting off the floor' },
    ],
    breathing: {
      ru: 'Вдох наверху, задержи дыхание на опускании, выдох на подъёме.',
      en: 'Inhale at the top, hold through the descent, exhale as you stand.',
    },
    muscles: ['quads', 'glutes', 'core', 'back', 'shoulders'],
    pattern: 'squat',
    equipment: ['dumbbells'],
    level: 2,
    unit: 'reps',
    secondsPerRep: 3.0,
    met: 6.0,
    loadable: true,
    scaling: { easier: 'db_goblet_squat', harder: 'db_thruster' },
    animation: 'db_front_squat',
    tags: ['lower'],
  },
  {
    id: 'db_thruster',
    slug: { ru: 'traster-s-gantelyami', en: 'dumbbell-thruster' },
    name: { ru: 'Трастер с гантелями', en: 'Dumbbell thruster' },
    shortName: { ru: 'Трастер', en: 'Thruster' },
    description: {
      ru: 'Трастер — фронтальный присед, который без паузы переходит в жим гантелей над головой. Это одно из самых тяжёлых и полезных упражнений в кроссфите: работают ноги, ягодицы, плечи, трицепсы и кор, а пульс взлетает за несколько повторений. Секрет — не жать руками отдельно, а разогнать гантели ногами из приседа и просто «дожать» их наверху.',
      en: 'The thruster is a front squat that flows straight into an overhead press without a pause. It is one of the hardest and most rewarding movements in CrossFit: legs, glutes, shoulders, triceps and core all work while your heart rate climbs within a few reps. The secret is not to press with the arms on their own but to launch the dumbbells with your legs out of the squat and simply finish them overhead.',
    },
    howTo: [
      {
        ru: 'Гантели на плечах, локти вперёд, стопы на ширине плеч.',
        en: 'Dumbbells on your shoulders, elbows forward, feet shoulder-width apart.',
      },
      {
        ru: 'Опустись в полный фронтальный присед: бёдра ниже параллели, корпус вертикален, гантели на плечах.',
        en: 'Drop into a full front squat: hips below parallel, torso upright, dumbbells on the shoulders.',
      },
      {
        ru: 'Мощно встань из приседа и, не останавливаясь, используй разгон ног, чтобы выжать гантели над головой до полного выпрямления рук.',
        en: 'Stand up powerfully and, without stopping, use the drive from your legs to press the dumbbells overhead to full lockout.',
      },
      {
        ru: 'Опусти гантели обратно на плечи и сразу уходи в следующий присед.',
        en: 'Lower the dumbbells back to your shoulders and sink straight into the next squat.',
      },
    ],
    cues: [
      { ru: 'Ноги толкают, руки дожимают', en: 'Legs drive, arms finish' },
      { ru: 'Одно слитное движение', en: 'One continuous movement' },
      { ru: 'Гантели над макушкой', en: 'Dumbbells over the crown of the head' },
    ],
    mistakes: [
      { ru: 'Пауза наверху приседа — теряется разгон', en: 'Pausing at the top of the squat and losing the drive' },
      { ru: 'Неполное выпрямление рук над головой', en: 'Arms not fully locked out overhead' },
      { ru: 'Гантели уходят вперёд, спина прогибается', en: 'Dumbbells drifting forward and the back arching' },
    ],
    breathing: {
      ru: 'Вдох на опускании в присед, выдох на жиме.',
      en: 'Inhale as you drop into the squat, exhale on the press.',
    },
    muscles: ['quads', 'glutes', 'shoulders', 'triceps', 'core', 'cardio'],
    pattern: 'full_body',
    equipment: ['dumbbells'],
    level: 2,
    unit: 'reps',
    secondsPerRep: 3.5,
    met: 8.0,
    loadable: true,
    scaling: { easier: 'db_front_squat' },
    animation: 'db_thruster',
    tags: ['lower', 'upper', 'push', 'cardio'],
  },
  {
    id: 'db_deadlift',
    slug: { ru: 'stanovaya-tyaga-s-gantelyami', en: 'dumbbell-deadlift' },
    name: { ru: 'Становая тяга с гантелями', en: 'Dumbbell deadlift' },
    shortName: { ru: 'Становая', en: 'Deadlift' },
    description: {
      ru: 'Становая тяга с гантелями — подъём веса с пола за счёт разгибания бёдер и колен с прямой спиной. Это самое важное движение для задней поверхности тела: ягодицы, бицепсы бедра и разгибатели спины учатся работать вместе, а ты — правильно поднимать любой предмет с пола. Гантели стоят по бокам от стоп, поэтому траектория короткая и удобная для новичка.',
      en: 'The dumbbell deadlift lifts a weight off the floor by extending the hips and knees with a flat back. It is the most important movement for the back of the body: glutes, hamstrings and spinal erectors learn to work together, and you learn to pick anything up from the floor properly. The dumbbells sit beside your feet, so the bar path is short and beginner-friendly.',
    },
    howTo: [
      {
        ru: 'Поставь гантели на пол по бокам от стоп. Стопы на ширине таза, носки вперёд.',
        en: 'Place the dumbbells on the floor beside your feet. Feet hip-width apart, toes forward.',
      },
      {
        ru: 'Отведи таз назад, согни колени и наклонись с прямой спиной, чтобы взять гантели; плечи над кистями, грудь раскрыта.',
        en: 'Push your hips back, bend your knees and hinge down with a flat back to grip the dumbbells; shoulders over your hands, chest open.',
      },
      {
        ru: 'Напряги пресс и встань, одновременно разгибая колени и бёдра; гантели идут вертикально вплотную к ногам.',
        en: 'Brace and stand up, extending knees and hips together; the dumbbells travel straight up, close to your legs.',
      },
      {
        ru: 'Наверху полностью выпрямись и сожми ягодицы, затем тем же путём опусти гантели на пол.',
        en: 'Stand fully tall and squeeze the glutes at the top, then lower the dumbbells to the floor along the same path.',
      },
    ],
    cues: [
      { ru: 'Спина прямая, грудь раскрыта', en: 'Flat back, chest open' },
      { ru: 'Гантели вплотную к ногам', en: 'Dumbbells close to the legs' },
      { ru: 'Толкай пол ногами', en: 'Push the floor away' },
    ],
    mistakes: [
      { ru: 'Округление спины при подъёме с пола', en: 'Rounding the back as the weight leaves the floor' },
      { ru: 'Таз поднимается раньше плеч', en: 'Hips shooting up before the shoulders' },
      { ru: 'Прогиб назад в верхней точке', en: 'Leaning back at the top' },
    ],
    breathing: {
      ru: 'Вдох и напряжение перед подъёмом, выдох в верхней точке.',
      en: 'Inhale and brace before the lift, exhale at the top.',
    },
    muscles: ['glutes', 'hamstrings', 'back', 'quads', 'core'],
    pattern: 'hinge',
    equipment: ['dumbbells'],
    level: 1,
    unit: 'reps',
    secondsPerRep: 3.0,
    met: 6.0,
    loadable: true,
    scaling: { easier: 'glute_bridge', harder: 'db_rdl' },
    animation: 'bell_deadlift',
    tags: ['lower'],
  },
  {
    id: 'db_rdl',
    slug: { ru: 'rumynskaya-tyaga-s-gantelyami', en: 'dumbbell-romanian-deadlift' },
    name: { ru: 'Румынская тяга с гантелями', en: 'Dumbbell Romanian deadlift' },
    shortName: { ru: 'Румынская тяга', en: 'Romanian deadlift' },
    description: {
      ru: 'Румынская тяга — наклон с гантелями на почти прямых ногах: движение идёт только в тазобедренном суставе, а гантели скользят вдоль бёдер вниз и вверх. В отличие от классической становой здесь вес не ставится на пол, и задняя поверхность бедра работает под постоянным натяжением. Это главное упражнение курса для бицепсов бедра и ягодиц и подготовка к махам гирей.',
      en: 'The Romanian deadlift is a hinge with dumbbells on nearly straight legs: the movement happens only at the hips while the dumbbells slide down and up along your thighs. Unlike the regular deadlift the weight never returns to the floor, so the hamstrings work under constant tension. It is the course’s key hamstring and glute exercise and the preparation for kettlebell swings.',
    },
    howTo: [
      {
        ru: 'Встань прямо с гантелями перед бёдрами, стопы на ширине таза, колени чуть согнуты.',
        en: 'Stand tall with the dumbbells in front of your thighs, feet hip-width apart, knees slightly bent.',
      },
      {
        ru: 'Отводи таз назад и наклоняйся с прямой спиной, гантели скользят вниз по ногам; колени почти не сгибаются.',
        en: 'Push your hips back and hinge forward with a flat back, dumbbells sliding down your legs; the knees barely bend.',
      },
      {
        ru: 'Опускайся, пока не почувствуешь сильное натяжение задней поверхности бедра, — обычно чуть ниже колена. Спина прямая.',
        en: 'Lower until you feel a strong stretch in the hamstrings, usually just below the knee. Back stays flat.',
      },
      {
        ru: 'Сожми ягодицы и вернись в вертикальное положение, продвигая таз вперёд.',
        en: 'Squeeze the glutes and return to standing by driving the hips forward.',
      },
    ],
    cues: [
      { ru: 'Таз назад, а не вниз', en: 'Hips back, not down' },
      { ru: 'Гантели по ногам', en: 'Dumbbells along the legs' },
      { ru: 'Спина прямая', en: 'Flat back' },
    ],
    mistakes: [
      { ru: 'Округлённая спина', en: 'Rounded back' },
      { ru: 'Слишком сильное сгибание коленей — получается присед', en: 'Bending the knees too much so it becomes a squat' },
      { ru: 'Гантели отходят от ног вперёд', en: 'Dumbbells drifting away from the legs' },
    ],
    breathing: {
      ru: 'Вдох на наклоне, выдох на подъёме.',
      en: 'Inhale as you hinge, exhale as you stand.',
    },
    muscles: ['hamstrings', 'glutes', 'back', 'core'],
    pattern: 'hinge',
    equipment: ['dumbbells'],
    level: 2,
    unit: 'reps',
    secondsPerRep: 3.5,
    met: 5.0,
    loadable: true,
    scaling: { easier: 'db_deadlift' },
    animation: 'db_rdl',
    tags: ['lower'],
  },
  {
    id: 'db_row',
    slug: { ru: 'tyaga-ganteli-v-naklone', en: 'dumbbell-bent-over-row' },
    name: { ru: 'Тяга гантели в наклоне', en: 'Dumbbell bent-over row' },
    shortName: { ru: 'Тяга в наклоне', en: 'Dumbbell row' },
    description: {
      ru: 'Тяга гантели в наклоне — основная горизонтальная тяга курса: ты наклоняешься с опорой свободной рукой на стул или колено и тянешь гантель к поясу. Работают широчайшие, ромбовидные, задние дельты и бицепс, а спина учится держать прямую линию под нагрузкой. Каждая сторона работает отдельно, поэтому слабая рука не прячется за сильной. Повторения указаны на каждую сторону.',
      en: 'The bent-over dumbbell row is the main horizontal pull of the course: you hinge forward, support yourself with the free hand on a chair or your knee and pull the dumbbell to your hip. It works the lats, rhomboids, rear delts and biceps while the back learns to hold a straight line under load. Each side works on its own, so the weaker arm cannot hide behind the stronger one. Reps are per side.',
    },
    howTo: [
      {
        ru: 'Поставь левую ладонь на сиденье стула или на левое колено, наклонись с прямой спиной почти до параллели с полом. В правой руке гантель, рука выпрямлена.',
        en: 'Place your left hand on a chair seat or your left knee and hinge forward with a flat back until your torso is close to parallel with the floor. Hold the dumbbell in your right hand, arm hanging straight.',
      },
      {
        ru: 'Опусти плечо от уха и тяни гантель к поясу, ведя локоть вдоль корпуса назад и вверх.',
        en: 'Draw your shoulder down and pull the dumbbell toward your hip, driving the elbow back and up along your side.',
      },
      {
        ru: 'В верхней точке локоть выше корпуса, лопатка сведена к позвоночнику, плечи и таз остаются в одной плоскости.',
        en: 'At the top the elbow is above your torso and the shoulder blade is pulled toward the spine; shoulders and hips stay square.',
      },
      {
        ru: 'Плавно опусти гантель до полного выпрямления руки. Сделай все повторения на одну сторону, затем поменяй.',
        en: 'Lower the dumbbell under control to a straight arm. Finish all reps on one side, then switch.',
      },
    ],
    cues: [
      { ru: 'Локоть к поясу', en: 'Elbow to the hip' },
      { ru: 'Спина ровная, как стол', en: 'Back flat like a table' },
      { ru: 'Не разворачивай корпус', en: 'Do not rotate the torso' },
    ],
    mistakes: [
      { ru: 'Корпус разворачивается вслед за гантелью', en: 'Torso twisting to lift the dumbbell' },
      { ru: 'Рывок и раскачка вместо тяги', en: 'Jerking and swinging instead of pulling' },
      { ru: 'Круглая спина', en: 'Rounded back' },
    ],
    breathing: {
      ru: 'Выдох на тяге, вдох при опускании.',
      en: 'Exhale as you row, inhale as you lower.',
    },
    muscles: ['lats', 'back', 'biceps', 'shoulders', 'core'],
    pattern: 'pull_horizontal',
    equipment: ['dumbbells'],
    level: 1,
    unit: 'reps',
    secondsPerRep: 2.5,
    met: 5.0,
    loadable: true,
    scaling: { harder: 'db_renegade_row' },
    animation: 'db_row',
    tags: ['upper', 'pull', 'unilateral'],
  },
  {
    id: 'db_shoulder_press',
    slug: { ru: 'zhim-ganteley-stoya', en: 'dumbbell-shoulder-press' },
    name: { ru: 'Жим гантелей стоя', en: 'Dumbbell shoulder press' },
    shortName: { ru: 'Жим стоя', en: 'Shoulder press' },
    description: {
      ru: 'Жим гантелей стоя — строгий жим над головой без помощи ног. Он строит плечи и трицепсы, а заодно учит держать корпус жёстким, когда вес уходит над головой: пресс и ягодицы не дают пояснице прогнуться. Это базовое вертикальное жимовое движение курса, из которого потом вырастают швунг и трастер.',
      en: 'The standing dumbbell shoulder press is a strict overhead press with no help from the legs. It builds the shoulders and triceps and teaches you to keep the trunk rigid while a load travels overhead: abs and glutes stop the lower back from arching. It is the course’s base vertical press, from which the push press and thruster grow.',
    },
    howTo: [
      {
        ru: 'Встань прямо, стопы на ширине таза, гантели на плечах, ладони смотрят вперёд или друг на друга, локти чуть впереди корпуса.',
        en: 'Stand tall, feet hip-width apart, dumbbells at your shoulders with palms forward or facing each other, elbows slightly in front of the body.',
      },
      {
        ru: 'Напряги пресс и ягодицы, чтобы рёбра были опущены, и выжми гантели вертикально вверх.',
        en: 'Brace your abs and glutes so the ribs stay down, then press the dumbbells straight up.',
      },
      {
        ru: 'В верхней точке полностью выпрями руки, гантели над макушкой, бицепсы у ушей.',
        en: 'At the top lock the arms out fully, dumbbells over the crown of your head, biceps by your ears.',
      },
      {
        ru: 'Плавно опусти гантели на плечи и повтори. Ноги не помогают.',
        en: 'Lower the dumbbells to your shoulders under control and repeat. The legs do not help.',
      },
    ],
    cues: [
      { ru: 'Рёбра вниз, пресс жёсткий', en: 'Ribs down, abs tight' },
      { ru: 'Гантели над макушкой', en: 'Dumbbells over the crown' },
      { ru: 'Полное выпрямление наверху', en: 'Full lockout at the top' },
    ],
    mistakes: [
      { ru: 'Прогиб в пояснице, рёбра выпячены', en: 'Arching the lower back and flaring the ribs' },
      { ru: 'Подталкивание ногами', en: 'Dipping the knees to help the press' },
      { ru: 'Гантели уходят вперёд, а не вверх', en: 'Dumbbells pressed forward instead of up' },
    ],
    breathing: {
      ru: 'Вдох внизу, выдох на жиме.',
      en: 'Inhale at the bottom, exhale as you press.',
    },
    muscles: ['shoulders', 'triceps', 'core'],
    pattern: 'push_vertical',
    equipment: ['dumbbells'],
    level: 1,
    unit: 'reps',
    secondsPerRep: 2.5,
    met: 5.0,
    loadable: true,
    scaling: { easier: 'pike_push_up', harder: 'db_push_press' },
    animation: 'overhead_press',
    tags: ['upper', 'push'],
  },
  {
    id: 'db_push_press',
    slug: { ru: 'shvung-s-gantelyami', en: 'dumbbell-push-press' },
    name: { ru: 'Швунг с гантелями', en: 'Dumbbell push press' },
    shortName: { ru: 'Швунг', en: 'Push press' },
    description: {
      ru: 'Швунг — жим над головой с коротким подседом и толчком ногами. Разгон снизу позволяет поднять больше веса и сделать больше повторений, чем в строгом жиме, а ещё учит передавать силу от ног к рукам через жёсткий корпус. Это тот же навык, что в трастере и рывке, только в самой простой форме. Подсед должен быть быстрым и неглубоким.',
      en: 'The push press is an overhead press with a short dip and drive from the legs. The leg drive lets you lift more weight and do more reps than a strict press, and it teaches you to transfer force from the legs to the arms through a rigid trunk. It is the same skill as the thruster and snatch in its simplest form. The dip should be quick and shallow.',
    },
    howTo: [
      {
        ru: 'Встань прямо, гантели на плечах, локти чуть впереди, стопы на ширине таза.',
        en: 'Stand tall with the dumbbells at your shoulders, elbows slightly forward, feet hip-width apart.',
      },
      {
        ru: 'Сделай короткий подсед: согни колени на 10–15 см, корпус остаётся строго вертикальным, пятки на полу.',
        en: 'Dip: bend the knees 10–15 cm with your torso perfectly upright and heels on the floor.',
      },
      {
        ru: 'Резко разогни ноги и, используя этот толчок, выжми гантели над головой до полного выпрямления рук.',
        en: 'Drive the legs straight explosively and use that momentum to press the dumbbells overhead to full lockout.',
      },
      {
        ru: 'Верни гантели на плечи, слегка амортизируя коленями, и повтори.',
        en: 'Bring the dumbbells back to your shoulders, absorbing with a slight knee bend, and repeat.',
      },
    ],
    cues: [
      { ru: 'Подсед короткий и быстрый', en: 'Short, fast dip' },
      { ru: 'Корпус вертикально', en: 'Torso vertical' },
      { ru: 'Толкай ногами, дожимай руками', en: 'Drive with the legs, finish with the arms' },
    ],
    mistakes: [
      { ru: 'Наклон корпуса вперёд в подседе', en: 'Leaning forward in the dip' },
      { ru: 'Слишком глубокий и медленный подсед', en: 'Dip too deep and too slow' },
      { ru: 'Пауза между подседом и жимом', en: 'Pausing between the dip and the drive' },
    ],
    breathing: {
      ru: 'Вдох перед подседом, выдох на толчке.',
      en: 'Inhale before the dip, exhale on the drive.',
    },
    muscles: ['shoulders', 'triceps', 'quads', 'glutes', 'core'],
    pattern: 'push_vertical',
    equipment: ['dumbbells'],
    level: 2,
    unit: 'reps',
    secondsPerRep: 2.0,
    met: 6.0,
    loadable: true,
    scaling: { easier: 'db_shoulder_press', harder: 'db_thruster' },
    animation: 'db_push_press',
    tags: ['upper', 'push', 'explosive'],
  },
];
