-- =============================================================================
-- Forma — 0004_content_seed: the course / workout catalogue the backend enforces.
--
-- GENERATED FILE — do not edit by hand.
-- Regenerate with:  node scripts/content/gen-seed.mjs
-- Source of truth:  content/courses/*.ts (validated by src/content/registry.ts)
--
-- Requires 0001_init.sql. Idempotent: upserts every row, then deletes what content
-- no longer has. Re-apply it after every content change that touches course ids,
-- workout ids or basePoints — create_order() rejects unknown course ids and
-- workout_sessions_guard clamps points to base_points from here.
-- =============================================================================

insert into public.courses (id, sort_order) values
  ('start', 1),
  ('engine', 2),
  ('dumbbells', 3),
  ('kettlebell', 4),
  ('athlete', 5)
on conflict (id) do update set sort_order = excluded.sort_order;

insert into public.workouts (course_id, id, base_points) values
  ('start', 'w_s01_sets', 100),
  ('start', 'w_s02_sets', 100),
  ('start', 'w_s03_pairs', 100),
  ('start', 'w_s04_bridges', 100),
  ('start', 'w_s05_three_rounds', 100),
  ('start', 'w_s06_amrap8', 100),
  ('start', 'w_s07_hundred_situps', 100),
  ('start', 'w_s08_emom_ladder', 100),
  ('start', 'w_s09_chipper_x2', 110),
  ('start', 'w_s10_every_3_min', 100),
  ('start', 'w_s11_emom8', 100),
  ('start', 'w_s12_step_ladder', 100),
  ('start', 'w_s13_amrap8_burpees', 110),
  ('start', 'w_s14_squats_4min', 80),
  ('start', 'w_s15_twenty_forty', 110),
  ('start', 'w_s16_amrap8_jacks', 100),
  ('start', 'w_s17_long_chipper', 120),
  ('start', 'w_s18_buy_in', 100),
  ('start', 'w_s19_three_windows', 110),
  ('start', 'w_s20_burpee_ladder', 120),
  ('start', 'w_s22_chipper_x2', 110),
  ('start', 'w_s23_amrap8_worms', 110),
  ('start', 'w_s24_steps_and_jumps', 110),
  ('start', 'w_test_start', 80),
  ('engine', 'w_bench_burpees', 150),
  ('engine', 'w_bench_cindy', 150),
  ('engine', 'w_chipper_a', 110),
  ('engine', 'w_chipper_b', 120),
  ('engine', 'w_easy_flow', 90),
  ('engine', 'w_engine_amrap10', 100),
  ('engine', 'w_engine_amrap15', 110),
  ('engine', 'w_engine_emom12', 100),
  ('engine', 'w_engine_tabata', 100),
  ('engine', 'w_hinge_core_a', 100),
  ('engine', 'w_hinge_core_b', 110),
  ('engine', 'w_hinge_core_c', 120),
  ('engine', 'w_squat_push_a', 100),
  ('engine', 'w_squat_push_b', 110),
  ('engine', 'w_squat_push_c', 120),
  ('engine', 'w_test', 80),
  ('dumbbells', 'w_bench_21_15_9', 150),
  ('dumbbells', 'w_bench_dt', 150),
  ('dumbbells', 'w_complex_a', 100),
  ('dumbbells', 'w_complex_b', 110),
  ('dumbbells', 'w_engine_amrap12', 100),
  ('dumbbells', 'w_engine_amrap15', 110),
  ('dumbbells', 'w_engine_emom12', 100),
  ('dumbbells', 'w_engine_tabata', 100),
  ('dumbbells', 'w_hinge_pull_a', 110),
  ('dumbbells', 'w_hinge_pull_b', 120),
  ('dumbbells', 'w_hinge_pull_c', 120),
  ('dumbbells', 'w_squat_press_a', 100),
  ('dumbbells', 'w_squat_press_b', 120),
  ('dumbbells', 'w_squat_press_c', 120),
  ('dumbbells', 'w_technique_flow', 90),
  ('dumbbells', 'w_test', 80),
  ('kettlebell', 'w_bench_swings_squats', 150),
  ('kettlebell', 'w_clean_press', 110),
  ('kettlebell', 'w_flow', 90),
  ('kettlebell', 'w_metcon_amrap15', 110),
  ('kettlebell', 'w_metcon_emom12', 100),
  ('kettlebell', 'w_metcon_ladder', 100),
  ('kettlebell', 'w_snatch_swing', 120),
  ('kettlebell', 'w_squat_press_a', 100),
  ('kettlebell', 'w_squat_press_b', 110),
  ('kettlebell', 'w_squat_press_c', 120),
  ('kettlebell', 'w_swing_school_a', 100),
  ('kettlebell', 'w_swing_school_b', 110),
  ('kettlebell', 'w_test', 80),
  ('athlete', 'w_bench_cindy', 150),
  ('athlete', 'w_bench_half_murph', 150),
  ('athlete', 'w_chipper_a', 110),
  ('athlete', 'w_chipper_b', 120),
  ('athlete', 'w_engine_amrap15', 110),
  ('athlete', 'w_engine_emom12', 100),
  ('athlete', 'w_engine_emom16', 110),
  ('athlete', 'w_engine_tabata', 100),
  ('athlete', 'w_murph_prep_a', 120),
  ('athlete', 'w_murph_prep_b', 130),
  ('athlete', 'w_pull_hinge_a', 110),
  ('athlete', 'w_pull_hinge_b', 120),
  ('athlete', 'w_pull_hinge_c', 120),
  ('athlete', 'w_skill_flow', 90),
  ('athlete', 'w_squat_push_a', 110),
  ('athlete', 'w_squat_push_b', 120),
  ('athlete', 'w_squat_push_c', 120),
  ('athlete', 'w_test', 80)
on conflict (course_id, id) do update set base_points = excluded.base_points;

-- Rows content no longer defines (workouts first: they reference courses).
delete from public.workouts where (course_id, id) not in (
  ('start', 'w_s01_sets'),
  ('start', 'w_s02_sets'),
  ('start', 'w_s03_pairs'),
  ('start', 'w_s04_bridges'),
  ('start', 'w_s05_three_rounds'),
  ('start', 'w_s06_amrap8'),
  ('start', 'w_s07_hundred_situps'),
  ('start', 'w_s08_emom_ladder'),
  ('start', 'w_s09_chipper_x2'),
  ('start', 'w_s10_every_3_min'),
  ('start', 'w_s11_emom8'),
  ('start', 'w_s12_step_ladder'),
  ('start', 'w_s13_amrap8_burpees'),
  ('start', 'w_s14_squats_4min'),
  ('start', 'w_s15_twenty_forty'),
  ('start', 'w_s16_amrap8_jacks'),
  ('start', 'w_s17_long_chipper'),
  ('start', 'w_s18_buy_in'),
  ('start', 'w_s19_three_windows'),
  ('start', 'w_s20_burpee_ladder'),
  ('start', 'w_s22_chipper_x2'),
  ('start', 'w_s23_amrap8_worms'),
  ('start', 'w_s24_steps_and_jumps'),
  ('start', 'w_test_start'),
  ('engine', 'w_bench_burpees'),
  ('engine', 'w_bench_cindy'),
  ('engine', 'w_chipper_a'),
  ('engine', 'w_chipper_b'),
  ('engine', 'w_easy_flow'),
  ('engine', 'w_engine_amrap10'),
  ('engine', 'w_engine_amrap15'),
  ('engine', 'w_engine_emom12'),
  ('engine', 'w_engine_tabata'),
  ('engine', 'w_hinge_core_a'),
  ('engine', 'w_hinge_core_b'),
  ('engine', 'w_hinge_core_c'),
  ('engine', 'w_squat_push_a'),
  ('engine', 'w_squat_push_b'),
  ('engine', 'w_squat_push_c'),
  ('engine', 'w_test'),
  ('dumbbells', 'w_bench_21_15_9'),
  ('dumbbells', 'w_bench_dt'),
  ('dumbbells', 'w_complex_a'),
  ('dumbbells', 'w_complex_b'),
  ('dumbbells', 'w_engine_amrap12'),
  ('dumbbells', 'w_engine_amrap15'),
  ('dumbbells', 'w_engine_emom12'),
  ('dumbbells', 'w_engine_tabata'),
  ('dumbbells', 'w_hinge_pull_a'),
  ('dumbbells', 'w_hinge_pull_b'),
  ('dumbbells', 'w_hinge_pull_c'),
  ('dumbbells', 'w_squat_press_a'),
  ('dumbbells', 'w_squat_press_b'),
  ('dumbbells', 'w_squat_press_c'),
  ('dumbbells', 'w_technique_flow'),
  ('dumbbells', 'w_test'),
  ('kettlebell', 'w_bench_swings_squats'),
  ('kettlebell', 'w_clean_press'),
  ('kettlebell', 'w_flow'),
  ('kettlebell', 'w_metcon_amrap15'),
  ('kettlebell', 'w_metcon_emom12'),
  ('kettlebell', 'w_metcon_ladder'),
  ('kettlebell', 'w_snatch_swing'),
  ('kettlebell', 'w_squat_press_a'),
  ('kettlebell', 'w_squat_press_b'),
  ('kettlebell', 'w_squat_press_c'),
  ('kettlebell', 'w_swing_school_a'),
  ('kettlebell', 'w_swing_school_b'),
  ('kettlebell', 'w_test'),
  ('athlete', 'w_bench_cindy'),
  ('athlete', 'w_bench_half_murph'),
  ('athlete', 'w_chipper_a'),
  ('athlete', 'w_chipper_b'),
  ('athlete', 'w_engine_amrap15'),
  ('athlete', 'w_engine_emom12'),
  ('athlete', 'w_engine_emom16'),
  ('athlete', 'w_engine_tabata'),
  ('athlete', 'w_murph_prep_a'),
  ('athlete', 'w_murph_prep_b'),
  ('athlete', 'w_pull_hinge_a'),
  ('athlete', 'w_pull_hinge_b'),
  ('athlete', 'w_pull_hinge_c'),
  ('athlete', 'w_skill_flow'),
  ('athlete', 'w_squat_push_a'),
  ('athlete', 'w_squat_push_b'),
  ('athlete', 'w_squat_push_c'),
  ('athlete', 'w_test')
);
delete from public.courses where id not in ('start', 'engine', 'dumbbells', 'kettlebell', 'athlete');
